<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (MANDATOSCD?,MANDATOSEXTERNOS?,NUMGABINETE?,ANEXO?,ANDAR?,TELEFONE?,FAX?,CODPESSOA?,TXTNOMEPARLAMENTAR?,TXTNOME?,IDECADASTRO?,NUMCARTEIRAPARLAMENTAR?,NUMERODAULTIMALEGISLATURA?,SIGPARTIDO?,SIGUFREPRESENTACAO?,DATNASCIMENTO?,NUMCPF?,GRAUINSTRUCAO?,NATURALIDADE?,PROFISSOES?,FILIACAO?,CONJUGE?,FILHOS?,LEGISLATURAS?,MANDATOSELETIVOS?,FILIACOESPARTIDARIAS?,AFASTAMENTOS?,SUPLENCIASEFETIVACOES?,LICENCAS?,PERDASMANDATO?,RENUNCIAS?,ATIVIDADESPARTIDARIAS?,ATIVIDADESPROFISSIONAIS?,ESTUDOSEGRAUSUNIVERSITARIOS?,SEMINARIOS?,ATIVIDADESPARLAMENTARES?,ATIVIDADESSINDICAIS?,CONSELHOS?,CONDECORACOES?,OBRASPUBLICADAS?,MISSOESOFICIAS?,OUTRASINFORMACOES?,FORMATODATANASCIMENTO?)+>
  <!ELEMENT MANDATOSCD (#PCDATA)>
  <!ELEMENT MANDATOSEXTERNOS (#PCDATA)>
  <!ELEMENT NUMGABINETE (#PCDATA)>
  <!ELEMENT ANEXO (#PCDATA)>
  <!ELEMENT ANDAR (#PCDATA)>
  <!ELEMENT TELEFONE (#PCDATA)>
  <!ELEMENT FAX (#PCDATA)>
  <!ELEMENT CODPESSOA (#PCDATA)>
  <!ELEMENT TXTNOMEPARLAMENTAR (#PCDATA)>
  <!ELEMENT TXTNOME (#PCDATA)>
  <!ELEMENT IDECADASTRO (#PCDATA)>
  <!ELEMENT NUMCARTEIRAPARLAMENTAR (#PCDATA)>
  <!ELEMENT NUMERODAULTIMALEGISLATURA (#PCDATA)>
  <!ELEMENT SIGPARTIDO (#PCDATA)>
  <!ELEMENT SIGUFREPRESENTACAO (#PCDATA)>
  <!ELEMENT DATNASCIMENTO (#PCDATA)>
  <!ELEMENT NUMCPF (#PCDATA)>
  <!ELEMENT GRAUINSTRUCAO (#PCDATA)>
  <!ELEMENT NATURALIDADE (#PCDATA)>
  <!ELEMENT PROFISSOES (#PCDATA)>
  <!ELEMENT FILIACAO (#PCDATA)>
  <!ELEMENT CONJUGE (#PCDATA)>
  <!ELEMENT FILHOS (#PCDATA)>
  <!ELEMENT LEGISLATURAS (#PCDATA)>
  <!ELEMENT MANDATOSELETIVOS (#PCDATA)>
  <!ELEMENT FILIACOESPARTIDARIAS (#PCDATA)>
  <!ELEMENT AFASTAMENTOS (#PCDATA)>
  <!ELEMENT SUPLENCIASEFETIVACOES (#PCDATA)>
  <!ELEMENT LICENCAS (#PCDATA)>
  <!ELEMENT PERDASMANDATO (#PCDATA)>
  <!ELEMENT RENUNCIAS (#PCDATA)>
  <!ELEMENT ATIVIDADESPARTIDARIAS (#PCDATA)>
  <!ELEMENT ATIVIDADESPROFISSIONAIS (#PCDATA)>
  <!ELEMENT ESTUDOSEGRAUSUNIVERSITARIOS (#PCDATA)>
  <!ELEMENT SEMINARIOS (#PCDATA)>
  <!ELEMENT ATIVIDADESPARLAMENTARES (#PCDATA)>
  <!ELEMENT ATIVIDADESSINDICAIS (#PCDATA)>
  <!ELEMENT CONSELHOS (#PCDATA)>
  <!ELEMENT CONDECORACOES (#PCDATA)>
  <!ELEMENT OBRASPUBLICADAS (#PCDATA)>
  <!ELEMENT MISSOESOFICIAS (#PCDATA)>
  <!ELEMENT OUTRASINFORMACOES (#PCDATA)>
  <!ELEMENT FORMATODATANASCIMENTO (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1915-1918, PR, . Dt. Posse: 03/05/1915; Deputado Federal, 1918-1921, PR, . Dt. Posse: 03/05/1918.</MANDATOSCD>
    <MANDATOSEXTERNOS></MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>123705</CODPESSOA>
    <TXTNOMEPARLAMENTAR>JO&#195;O PERNETA</TXTNOMEPARLAMENTAR>
    <TXTNOME>Jo&#227;o David Perneta</TXTNOME>
    <IDECADASTRO>2428</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR></NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>31</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>PR</SIGUFREPRESENTACAO>
    <DATNASCIMENTO></DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO></GRAUINSTRUCAO>
    <NATURALIDADE>,</NATURALIDADE>
    <PROFISSOES></PROFISSOES>
    <FILIACAO></FILIACAO>
    <CONJUGE></CONJUGE>
    <FILHOS></FILHOS>
    <LEGISLATURAS>1915-1918 e 1918-1921.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1915-1918, PR, . Dt. Posse: 03/05/1915; Deputado Federal, 1918-1921, PR, . Dt. Posse: 03/05/1918.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS></FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES></SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS></ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS></ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS></ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES>CD:&#10;MESA: 1&#186; Suplente, 1917-1919; 2&#186; Suplente, 1915-1916.</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES></OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1915-1918, PE, . Dt. Posse: 03/05/1915.</MANDATOSCD>
    <MANDATOSEXTERNOS></MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>123707</CODPESSOA>
    <TXTNOMEPARLAMENTAR>CALDAS FILHO</TXTNOMEPARLAMENTAR>
    <TXTNOME>Thomaz Lins Caldas Filho</TXTNOME>
    <IDECADASTRO>2429</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR></NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>30</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>PE</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>01/01/68</DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO></GRAUINSTRUCAO>
    <NATURALIDADE>Recife, PE</NATURALIDADE>
    <PROFISSOES>Advogado e Jornalista</PROFISSOES>
    <FILIACAO>Thomaz Lins Caldas </FILIACAO>
    <CONJUGE></CONJUGE>
    <FILHOS></FILHOS>
    <LEGISLATURAS>1915-1918</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1915-1918, PE, . Dt. Posse: 03/05/1915.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS></FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES></SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS></ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Ainda estudante de direi</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Faculdade de Direito, Recife</ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES></ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES></OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>3</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1915-1918, PE, . Dt. Posse: 03/05/1915; Deputado Federal, 1921-1924, PE, . Dt. Posse: 03/05/1921; Deputado Federal, 1924-1927, PE, . Dt. Posse: 03/05/1924; Deputado Federal, 1927-1930, PE, . Dt. Posse: 02/05/1927; Deputado Federal, 1930-1930, PE, . Dt. Posse: 02/05/1930.</MANDATOSCD>
    <MANDATOSEXTERNOS></MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>123708</CODPESSOA>
    <TXTNOMEPARLAMENTAR>COSTA RIBEIRO</TXTNOMEPARLAMENTAR>
    <TXTNOME>Antonio Jos&#233; da Costa Ribeiro &#40;2&#186;&#41;</TXTNOME>
    <IDECADASTRO>2430</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR></NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>35</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>PE</SIGUFREPRESENTACAO>
    <DATNASCIMENTO></DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO></GRAUINSTRUCAO>
    <NATURALIDADE>,</NATURALIDADE>
    <PROFISSOES></PROFISSOES>
    <FILIACAO></FILIACAO>
    <CONJUGE></CONJUGE>
    <FILHOS></FILHOS>
    <LEGISLATURAS>1915-1918, 1921-1924, 1924-1927, 1927-1930 e 1930-1930.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1915-1918, PE, . Dt. Posse: 03/05/1915; Deputado Federal, 1921-1924, PE, . Dt. Posse: 03/05/1921; Deputado Federal, 1924-1927, PE, . Dt. Posse: 03/05/1924; Deputado Federal, 1927-1930, PE, . Dt. Posse: 02/05/1927; Deputado Federal, 1930-1930, PE, . Dt. Posse: 02/05/1930.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS></FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES></SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS></ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS></ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS></ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES>CD:&#10;MESA: 1&#186; Secret&#225;rio, 1915-1917.</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES></OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1916-1918, PE, . Dt. Posse: 09/09/1916.</MANDATOSCD>
    <MANDATOSEXTERNOS></MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>123709</CODPESSOA>
    <TXTNOMEPARLAMENTAR>F&#193;BIO DE BARROS</TXTNOMEPARLAMENTAR>
    <TXTNOME>F&#225;bio da Silveira Barros</TXTNOME>
    <IDECADASTRO>2431</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR></NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>30</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>PE</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>16/10/66</DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO></GRAUINSTRUCAO>
    <NATURALIDADE>Gameleira, PE</NATURALIDADE>
    <PROFISSOES></PROFISSOES>
    <FILIACAO></FILIACAO>
    <CONJUGE></CONJUGE>
    <FILHOS></FILHOS>
    <LEGISLATURAS>1915-1918</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1916-1918, PE, . Dt. Posse: 09/09/1916.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS></FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES></SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS></ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS></ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS></ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES></ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES>Eleito para ocupar </OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1915-1918, PE, . Dt. Posse: 03/05/1915; Deputado Federal, 1918-1921, PE, . Dt. Posse: 01/06/1918.</MANDATOSCD>
    <MANDATOSEXTERNOS></MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>123710</CODPESSOA>
    <TXTNOMEPARLAMENTAR>GERV&#193;SIO FIORAVANTI</TXTNOMEPARLAMENTAR>
    <TXTNOME>Gervasio Fioravante Pires Ferreira</TXTNOME>
    <IDECADASTRO>2432</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR></NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>31</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>PE</SIGUFREPRESENTACAO>
    <DATNASCIMENTO></DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO></GRAUINSTRUCAO>
    <NATURALIDADE>,</NATURALIDADE>
    <PROFISSOES></PROFISSOES>
    <FILIACAO></FILIACAO>
    <CONJUGE></CONJUGE>
    <FILHOS></FILHOS>
    <LEGISLATURAS>1915-1918 e 1918-1921.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1915-1918, PE, . Dt. Posse: 03/05/1915; Deputado Federal, 1918-1921, PE, . Dt. Posse: 01/06/1918.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS></FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES></SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS></ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS></ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS></ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES></ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES></OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1916-1918, PE, . Dt. Posse: 30/08/1916; Deputado Federal, 1921-1924, PE, . Dt. Posse: 03/05/1921; Deputado Federal, 1924-1927, PE, . Dt. Posse: 25/12/1924.</MANDATOSCD>
    <MANDATOSEXTERNOS></MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>123711</CODPESSOA>
    <TXTNOMEPARLAMENTAR>GOUVEIA DE BARROS</TXTNOMEPARLAMENTAR>
    <TXTNOME>Manoel Gouv&#234;a de Barros</TXTNOME>
    <IDECADASTRO>2433</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR></NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>33</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>PE</SIGUFREPRESENTACAO>
    <DATNASCIMENTO></DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO></GRAUINSTRUCAO>
    <NATURALIDADE>,</NATURALIDADE>
    <PROFISSOES></PROFISSOES>
    <FILIACAO></FILIACAO>
    <CONJUGE></CONJUGE>
    <FILHOS></FILHOS>
    <LEGISLATURAS>1915-1918, 1921-1924 e 1924-1927.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1916-1918, PE, . Dt. Posse: 30/08/1916; Deputado Federal, 1921-1924, PE, . Dt. Posse: 03/05/1921; Deputado Federal, 1924-1927, PE, . Dt. Posse: 25/12/1924.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS></FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES></SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS></ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS></ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS></ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES></ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES></OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1915-1918, PE, . Dt. Posse: 03/05/1915.</MANDATOSCD>
    <MANDATOSEXTERNOS></MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>123712</CODPESSOA>
    <TXTNOMEPARLAMENTAR>JULIO MARANH&#195;O</TXTNOMEPARLAMENTAR>
    <TXTNOME>Julio Carneiro de Albuquerque Maranh&#227;</TXTNOME>
    <IDECADASTRO>2434</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR></NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>30</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>PE</SIGUFREPRESENTACAO>
    <DATNASCIMENTO></DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO></GRAUINSTRUCAO>
    <NATURALIDADE>,</NATURALIDADE>
    <PROFISSOES></PROFISSOES>
    <FILIACAO></FILIACAO>
    <CONJUGE></CONJUGE>
    <FILHOS></FILHOS>
    <LEGISLATURAS>1915-1918</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1915-1918, PE, . Dt. Posse: 03/05/1915.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS></FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES></SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS></ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS></ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS></ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES></ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES></OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1915-1918, PE, . Dt. Posse: 03/05/1915.</MANDATOSCD>
    <MANDATOSEXTERNOS></MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>123713</CODPESSOA>
    <TXTNOMEPARLAMENTAR>RODOLFO ARA&#218;JO</TXTNOMEPARLAMENTAR>
    <TXTNOME>Rodolpho de Albuquerque Araujo</TXTNOME>
    <IDECADASTRO>2435</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR></NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>30</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>PE</SIGUFREPRESENTACAO>
    <DATNASCIMENTO></DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO></GRAUINSTRUCAO>
    <NATURALIDADE>,</NATURALIDADE>
    <PROFISSOES></PROFISSOES>
    <FILIACAO></FILIACAO>
    <CONJUGE></CONJUGE>
    <FILHOS></FILHOS>
    <LEGISLATURAS>1915-1918</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1915-1918, PE, . Dt. Posse: 03/05/1915.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS></FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES></SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS></ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS></ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS></ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES></ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES></OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1915-1918, RN, . Dt. Posse: 03/05/1915; Deputado Federal, 1918-1921, RN, . Dt. Posse: 03/05/1918.</MANDATOSCD>
    <MANDATOSEXTERNOS>Deputado Estadual, N/D, Partido: N/D,&#10;Per&#237;odo: 1891 a , Constituinte</MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>123714</CODPESSOA>
    <TXTNOMEPARLAMENTAR>AFONSO BARATA</TXTNOMEPARLAMENTAR>
    <TXTNOME>Affonso Moreira de Loyola Barata</TXTNOME>
    <IDECADASTRO>2436</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR></NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>31</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>RN</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>20/09/62</DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Natal, RN</NATURALIDADE>
    <PROFISSOES></PROFISSOES>
    <FILIACAO></FILIACAO>
    <CONJUGE></CONJUGE>
    <FILHOS></FILHOS>
    <LEGISLATURAS>1915-1918 e 1918-1921.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Estadual &#40;Constituinte&#41;, 1891-, , ; Deputado Federal, 1915-1918, RN, . Dt. Posse: 03/05/1915; Deputado Federal, 1918-1921, RN, . Dt. Posse: 03/05/1918.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS></FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES></SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS></ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>M&#233;dico Adjunto do Ex&#233;rci</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Estudos preparat&#243;rios em nat</ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES></ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES></OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1915-1918, RS, . Dt. Posse: 03/05/1915; Deputado Federal, 1918-1921, RS, . Dt. Posse: 03/05/1918; Deputado Federal, 1921-1924, RS, . Dt. Posse: 03/05/1921; Deputado Federal, 1927-1930, RS, . Dt. Posse: 16/05/1927.</MANDATOSCD>
    <MANDATOSEXTERNOS></MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>123715</CODPESSOA>
    <TXTNOMEPARLAMENTAR>&#193;LVARO BATISTA</TXTNOMEPARLAMENTAR>
    <TXTNOME>&#193;lvaro Baptista</TXTNOME>
    <IDECADASTRO>2437</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR></NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>34</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>RS</SIGUFREPRESENTACAO>
    <DATNASCIMENTO></DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO></GRAUINSTRUCAO>
    <NATURALIDADE>,</NATURALIDADE>
    <PROFISSOES></PROFISSOES>
    <FILIACAO></FILIACAO>
    <CONJUGE></CONJUGE>
    <FILHOS></FILHOS>
    <LEGISLATURAS>1915-1918, 1918-1921, 1921-1924 e 1927-1930.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1915-1918, RS, . Dt. Posse: 03/05/1915; Deputado Federal, 1918-1921, RS, . Dt. Posse: 03/05/1918; Deputado Federal, 1921-1924, RS, . Dt. Posse: 03/05/1921; Deputado Federal, 1927-1930, RS, . Dt. Posse: 16/05/1927.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS></FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES></SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS></ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS></ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS></ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES></ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES></OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1915-1918, RS, . Dt. Posse: 03/05/1915; Deputado Federal, 1921-1924, RS, . Dt. Posse: 03/05/1921; Deputado Federal, 1924-1927, RS, . Dt. Posse: 01/07/1924; Deputado Federal, 1930-1930, RS, . Dt. Posse: 02/05/1930.</MANDATOSCD>
    <MANDATOSEXTERNOS></MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>123716</CODPESSOA>
    <TXTNOMEPARLAMENTAR>ANTUNES MACIEL</TXTNOMEPARLAMENTAR>
    <TXTNOME>Francisco Antunes Maciel J&#250;nior</TXTNOME>
    <IDECADASTRO>2438</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR></NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>35</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>RS</SIGUFREPRESENTACAO>
    <DATNASCIMENTO></DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO></GRAUINSTRUCAO>
    <NATURALIDADE>,</NATURALIDADE>
    <PROFISSOES></PROFISSOES>
    <FILIACAO></FILIACAO>
    <CONJUGE></CONJUGE>
    <FILHOS></FILHOS>
    <LEGISLATURAS>1915-1918, 1921-1924, 1924-1927 e 1930-1930.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1915-1918, RS, . Dt. Posse: 03/05/1915; Deputado Federal, 1921-1924, RS, . Dt. Posse: 03/05/1921; Deputado Federal, 1924-1927, RS, . Dt. Posse: 01/07/1924; Deputado Federal, 1930-1930, RS, . Dt. Posse: 02/05/1930.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS></FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES></SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS></ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS></ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS></ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES></ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES></OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1916-1918, RS, . Dt. Posse: 28/09/1916; Deputado Federal, 1918-1921, RS, . Dt. Posse: 03/05/1918; Deputado Federal, 1921-1924, RS, . Dt. Posse: 05/05/1921; Deputado Federal, 1924-1927, RS, . Dt. Posse: 03/07/1924; Deputado Federal, 1927-1930, RS, . Dt. Posse: 02/05/1927; Deputado Federal, 1930-1930, RS, . Dt. Posse: 02/05/1930.</MANDATOSCD>
    <MANDATOSEXTERNOS></MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>123717</CODPESSOA>
    <TXTNOMEPARLAMENTAR>BARBOSA GON&#199;ALVES</TXTNOMEPARLAMENTAR>
    <TXTNOME>Jos&#233; Barbosa Gon&#231;alves</TXTNOME>
    <IDECADASTRO>2439</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR></NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>35</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>RS</SIGUFREPRESENTACAO>
    <DATNASCIMENTO></DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO></GRAUINSTRUCAO>
    <NATURALIDADE>,</NATURALIDADE>
    <PROFISSOES></PROFISSOES>
    <FILIACAO></FILIACAO>
    <CONJUGE></CONJUGE>
    <FILHOS></FILHOS>
    <LEGISLATURAS>1915-1918, 1918-1921, 1921-1924, 1924-1927, 1927-1930 e 1930-1930.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1916-1918, RS, . Dt. Posse: 28/09/1916; Deputado Federal, 1918-1921, RS, . Dt. Posse: 03/05/1918; Deputado Federal, 1921-1924, RS, . Dt. Posse: 05/05/1921; Deputado Federal, 1924-1927, RS, . Dt. Posse: 03/07/1924; Deputado Federal, 1927-1930, RS, . Dt. Posse: 02/05/1927; Deputado Federal, 1930-1930, RS, . Dt. Posse: 02/05/1930.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS></FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES>Assumiu como suplente </SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS></ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS></ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS></ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES></ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES></OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1915-1918, RS, . Dt. Posse: 03/05/1915; Deputado Federal, 1921-1924, RS, . Dt. Posse: 05/05/1921.</MANDATOSCD>
    <MANDATOSEXTERNOS></MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>123719</CODPESSOA>
    <TXTNOMEPARLAMENTAR>RAFAEL CABEDA</TXTNOMEPARLAMENTAR>
    <TXTNOME>Raphael Cabeda</TXTNOME>
    <IDECADASTRO>2441</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR></NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>32</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>RS</SIGUFREPRESENTACAO>
    <DATNASCIMENTO></DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO></GRAUINSTRUCAO>
    <NATURALIDADE>,</NATURALIDADE>
    <PROFISSOES></PROFISSOES>
    <FILIACAO></FILIACAO>
    <CONJUGE></CONJUGE>
    <FILHOS></FILHOS>
    <LEGISLATURAS>1915-1918 e 1921-1924.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1915-1918, RS, . Dt. Posse: 03/05/1915; Deputado Federal, 1921-1924, RS, . Dt. Posse: 05/05/1921.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS></FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES></SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS></ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS></ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS></ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES></ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES></OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1915-1918, RJ, . Dt. Posse: 04/06/1915.</MANDATOSCD>
    <MANDATOSEXTERNOS></MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>