<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (MANDATOSCD?,MANDATOSEXTERNOS?,NUMGABINETE?,ANEXO?,ANDAR?,TELEFONE?,FAX?,CODPESSOA?,TXTNOMEPARLAMENTAR?,TXTNOME?,IDECADASTRO?,NUMCARTEIRAPARLAMENTAR?,NUMERODAULTIMALEGISLATURA?,SIGPARTIDO?,SIGUFREPRESENTACAO?,DATNASCIMENTO?,NUMCPF?,GRAUINSTRUCAO?,NATURALIDADE?,PROFISSOES?,FILIACAO?,CONJUGE?,FILHOS?,LEGISLATURAS?,MANDATOSELETIVOS?,FILIACOESPARTIDARIAS?,AFASTAMENTOS?,SUPLENCIASEFETIVACOES?,LICENCAS?,PERDASMANDATO?,RENUNCIAS?,ATIVIDADESPARTIDARIAS?,ATIVIDADESPROFISSIONAIS?,ESTUDOSEGRAUSUNIVERSITARIOS?,SEMINARIOS?,ATIVIDADESPARLAMENTARES?,ATIVIDADESSINDICAIS?,CONSELHOS?,CONDECORACOES?,OBRASPUBLICADAS?,MISSOESOFICIAS?,OUTRASINFORMACOES?,FORMATODATANASCIMENTO?)+>
  <!ELEMENT MANDATOSCD (#PCDATA)>
  <!ELEMENT MANDATOSEXTERNOS (#PCDATA)>
  <!ELEMENT NUMGABINETE (#PCDATA)>
  <!ELEMENT ANEXO (#PCDATA)>
  <!ELEMENT ANDAR (#PCDATA)>
  <!ELEMENT TELEFONE (#PCDATA)>
  <!ELEMENT FAX (#PCDATA)>
  <!ELEMENT CODPESSOA (#PCDATA)>
  <!ELEMENT TXTNOMEPARLAMENTAR (#PCDATA)>
  <!ELEMENT TXTNOME (#PCDATA)>
  <!ELEMENT IDECADASTRO (#PCDATA)>
  <!ELEMENT NUMCARTEIRAPARLAMENTAR (#PCDATA)>
  <!ELEMENT NUMERODAULTIMALEGISLATURA (#PCDATA)>
  <!ELEMENT SIGPARTIDO (#PCDATA)>
  <!ELEMENT SIGUFREPRESENTACAO (#PCDATA)>
  <!ELEMENT DATNASCIMENTO (#PCDATA)>
  <!ELEMENT NUMCPF (#PCDATA)>
  <!ELEMENT GRAUINSTRUCAO (#PCDATA)>
  <!ELEMENT NATURALIDADE (#PCDATA)>
  <!ELEMENT PROFISSOES (#PCDATA)>
  <!ELEMENT FILIACAO (#PCDATA)>
  <!ELEMENT CONJUGE (#PCDATA)>
  <!ELEMENT FILHOS (#PCDATA)>
  <!ELEMENT LEGISLATURAS (#PCDATA)>
  <!ELEMENT MANDATOSELETIVOS (#PCDATA)>
  <!ELEMENT FILIACOESPARTIDARIAS (#PCDATA)>
  <!ELEMENT AFASTAMENTOS (#PCDATA)>
  <!ELEMENT SUPLENCIASEFETIVACOES (#PCDATA)>
  <!ELEMENT LICENCAS (#PCDATA)>
  <!ELEMENT PERDASMANDATO (#PCDATA)>
  <!ELEMENT RENUNCIAS (#PCDATA)>
  <!ELEMENT ATIVIDADESPARTIDARIAS (#PCDATA)>
  <!ELEMENT ATIVIDADESPROFISSIONAIS (#PCDATA)>
  <!ELEMENT ESTUDOSEGRAUSUNIVERSITARIOS (#PCDATA)>
  <!ELEMENT SEMINARIOS (#PCDATA)>
  <!ELEMENT ATIVIDADESPARLAMENTARES (#PCDATA)>
  <!ELEMENT ATIVIDADESSINDICAIS (#PCDATA)>
  <!ELEMENT CONSELHOS (#PCDATA)>
  <!ELEMENT CONDECORACOES (#PCDATA)>
  <!ELEMENT OBRASPUBLICADAS (#PCDATA)>
  <!ELEMENT MISSOESOFICIAS (#PCDATA)>
  <!ELEMENT OUTRASINFORMACOES (#PCDATA)>
  <!ELEMENT FORMATODATANASCIMENTO (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1963-1967, RS, ARENA. Dt. Posse: 02/02/1963.</MANDATOSCD>
    <MANDATOSEXTERNOS>Vereador, Tr&#234;s Passos/RS, Partido: PRP,&#10;Per&#237;odo: 1951 a 1955&#10;Deputado Estadual, RS, Partido: PRP,&#10;Per&#237;odo: 1955 a 1963&#10;Governador, RS, Partido: N/D,&#10;Per&#237;odo: 1960 a 1960, Interino&#10;Deputado Estadual, RS, Partido: ARENA,&#10;Per&#237;odo: 1971 a 1975</MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>122315</CODPESSOA>
    <TXTNOMEPARLAMENTAR>PEDRO ANSCHAU</TXTNOMEPARLAMENTAR>
    <TXTNOME>Pedro Affonso Anschau</TXTNOME>
    <IDECADASTRO>131101</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR>226</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>42</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>ARENA</SIGPARTIDO>
    <SIGUFREPRESENTACAO>RS</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>17/11/25</DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO></GRAUINSTRUCAO>
    <NATURALIDADE>Cerro Largo, RS</NATURALIDADE>
    <PROFISSOES>Contador e Comerciante</PROFISSOES>
    <FILIACAO>Jac&#243; Anschau e Maria Luiza Anschau</FILIACAO>
    <CONJUGE>Maria Victoria Wenzel Anschau</CONJUGE>
    <FILHOS>Delci Maria Anschau, Eloi Afonso Anschau, Jos&#233; Luiz Anschau, Maria Goretti Anschau e Vera Beatriz Anschau</FILHOS>
    <LEGISLATURAS>1963-1967</LEGISLATURAS>
    <MANDATOSELETIVOS>Vereador, 1951-1955, Tr&#234;s Passos, RS, PRP; Deputado Estadual, 1955-1963, RS, PRP; Governador &#40;Interino&#41;, 1960, RS, ; Deputado Federal, 1963-1967, RS, ARENA. Dt. Posse: 02/02/1963; Deputado Estadual, 1971-1975, RS, ARENA.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>PRP; ARENA, 1965-.</FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES></SUPLENCIASEFETIVACOES>
    <LICENCAS>Licenciou-se do mandato de Deputado Federal na Legislatura 1963-1967, para tratamento de sa&#250;de, de 16 de setembro a 17 de outubro de 1963.</LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS>Vice-l&#237;der, PRP, 1964.</ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Assessor na &#225;rea de seguros, Companhia do Sul de Abastecimentos dentre outras empresas, 1975-1992.</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Col&#233;gio Santo In&#225;cio, Monte Negro, RS; Contabilidade,1945 e Secretariado em Monte Negro, RS.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES>C&#194;MARAS MUNICIPAIS, ASSEMBL&#201;IAS LEGISLATIVAS E C&#194;MARA LEGISLATIVA DO DF:&#10;ALRS: Mesa: Primeiro-Secret&#225;rio, 1956-1958, e Presidente, 1960; Comiss&#245;es de Agricultura, de Divis&#227;o Territorial e de Educa&#231;&#227;o e Cultura.&#10;&#10;CONGRESSO NACIONAL:&#10;COMISS&#213;ES MISTAS: Veto ao PL 3.567-B/66, que disp&#245;e sobre a inspe&#231;&#227;o industrial e sanit&#225;ria dos produtos de origem animal: Vice-Presidente, 1967.&#10;&#10;C&#194;MARA DOS DEPUTADOS:&#10;COMISS&#213;ES PERMANENTES: Seguran&#231;a Nacional: Suplente, 1963.</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS>Problema agr&#225;rio brasileiro.</OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES></OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal &#40;Constituinte&#41;, 1933-1935, MG, . Dt. Posse: 15/11/1933; Deputado Federal, 1935-1937, MG, . Dt. Posse: 03/05/1935; Deputado Federal, 1955, MG, . Dt. Posse: 19/09/1955; Deputado Federal, 1963, MG, UDN; Deputado Federal, 1967, MG, UDN.</MANDATOSCD>
    <MANDATOSEXTERNOS>Deputado Estadual, N/D, Partido: UDN,&#10;Per&#237;odo: 1947 a 1951, Constituinte&#10;Vice-Presidente da Rep&#250;blica, N/D, Partido: N/D,&#10;Per&#237;odo: 1967 a 1969</MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>122316</CODPESSOA>
    <TXTNOMEPARLAMENTAR>PEDRO ALEIXO</TXTNOMEPARLAMENTAR>
    <TXTNOME>Pedro Aleixo</TXTNOME>
    <IDECADASTRO>131102</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR>227</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>42</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>ARENA</SIGPARTIDO>
    <SIGUFREPRESENTACAO>MG</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>01/08/01</DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Mariana, MG</NATURALIDADE>
    <PROFISSOES>Advogado, Jornalista e Professor</PROFISSOES>
    <FILIACAO>Jos&#233; Caetano Aleixo e &#218;rsula Martins Aleixo</FILIACAO>
    <CONJUGE>Maria Stuart Brandi Aleixo</CONJUGE>
    <FILHOS>Heloisa Aleixo Lustosa de Andrade, Jos&#233; Carlos Brandi Aleixo, Maur&#237;cio Brandi Aleixo e S&#233;rgio Brandi Aleixo</FILHOS>
    <LEGISLATURAS>1934-1935, 1935-1937, 1955-1959, 1959-1963 e 1963-1967.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal &#40;Constituinte&#41;, 1933-1935, MG, . Dt. Posse: 15/11/1933; Deputado Federal, 1935-1937, MG, . Dt. Posse: 03/05/1935; Deputado Estadual &#40;Constituinte&#41;, 1947-1951, , UDN; Deputado Federal, 1955, MG, . Dt. Posse: 19/09/1955; Deputado Federal, -1963, MG, UDN; Deputado Federal, -1967, MG, UDN; Vice-Presidente da Rep&#250;blica, 1967-1969, , .</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>UDN; PP; ARENA</FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES>Assumiu, como Suplente</SUPLENCIASEFETIVACOES>
    <LICENCAS>Licenciou-se do mandato de Deputado Federal, na Legislatura 1963-1967, para assumir o Cargo de Ministro da Educa&#231;&#227;o, de  10 de janeiro a 30 de junho de 1966.</LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS>Fundador do Partido Progressista - PP de Mina</ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Presidente, Comiss&#227;o de Revis&#227;o Administrativa do Estado de Minas Gerais, 1933; Secret&#225;rio do Interior, 1947-1950; Ministro da Educa&#231;&#227;o e Cultura, 1966; Professor de Direito Penal,1956- e Direito I</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Col&#233;gio Furtado de Menezes; Col&#233;gio Azevedo Coutinho; Gin&#225;sio de Ouro Preto; Gin&#225;sio Mineiro de Belo Horizonte; Col&#233;gio Caetano Azevedo, 1971; Fac. de Direito, UFMG, 1922.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES>CONGRESSO NACIONAL:&#10;COMISS&#213;ES MISTAS: PL 1293/59, que cria o Condom&#237;no Rural do Piau&#237;: Membro, 1963; PL 4540/62 que or&#231;a a Receita e fixa a Despesa do Distrito Federal para o exerc&#237;cio financeiro de 1963: Membro, 1963; PL 2568/61, que transforma em unidades universit&#225;rias os cursos de Odontologia e de Farm&#225;cia da Universidade de Minas Gerais: Membro, 1963; estudo do Projeto de Constitui&#231;&#227;o: Presidente, 1967.&#10;&#10;C&#194;MARA DOS DEPUTADOS: &#10;MESA DIRETORA: Presidente, 04.mai-09.nov.1937 &#40;Di&#225;rio do Poder Legislativo, 05.05.1937, p.30.214/6&#41;.&#10;COMISS&#213;ES PERMANENTES: Constitui&#231;&#227;o e Justi&#231;a: Membro, 1963.&#10;Comiss&#227;o de Revis&#227;o Administrativa do Estado: Presidente, 1933.</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS>Diretor, Centro Acad</ATIVIDADESSINDICAIS>
    <CONSELHOS>Membro, Conselho De</CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS>O peculato no Direito Penal brasileiro, 1956; Sigilo prof</OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES>Pai - Jos&#233; Caetano </OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1955-1959, MA, PSD. Dt. Posse: 07/03/1955; Deputado Federal, 1/7/1960-7/10/1960, MA, UDN. Dt. Posse: 01/07/1960; Deputado Federal, 1963-1967, MA, UDN. Dt. Posse: 01/02/1963.</MANDATOSCD>
    <MANDATOSEXTERNOS></MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>122317</CODPESSOA>
    <TXTNOMEPARLAMENTAR>PEDRO BRAGA</TXTNOMEPARLAMENTAR>
    <TXTNOME>Pedro Braga Filho</TXTNOME>
    <IDECADASTRO>131103</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR>228</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>42</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>UDN</SIGPARTIDO>
    <SIGUFREPRESENTACAO>MA</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>16/04/18</DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Barra do Corda, MA</NATURALIDADE>
    <PROFISSOES>M&#233;dico</PROFISSOES>
    <FILIACAO>Pedro Pereira Braga e Maria da Rocha Holanda Braga</FILIACAO>
    <CONJUGE>Corina Desir&#233;e da Costa Braga</CONJUGE>
    <FILHOS>Pedro Braga Neto e Tereza Cristina da Costa Braga</FILHOS>
    <LEGISLATURAS>1955-1959, 1959-1963 e 1963-1967.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1955-1959, MA, PSD. Dt. Posse: 07/03/1955; Deputado Federal, 1/7/1960-7/10/1960, MA, UDN. Dt. Posse: 01/07/1960; Deputado Federal, 1963-1967, MA, UDN. Dt. Posse: 01/02/1963.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>PSD, -1957; MDB; UDN, 1957-.</FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES>Assumiu, como Suplente</SUPLENCIASEFETIVACOES>
    <LICENCAS>Licenciou-se do mandato de Deputado Federal, na Legislatura 1955-1959, para tratamento de sa&#250;de, de 1 a 14 de junho de 1955; de 28 de julho a 28 de setembro de 1956; de 8 de fevereiro a 3 de abril de 1957; de 14 maio a 12 de julho de 1957.&#10;Licenciou-se do mandato de Deputado F</LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS>Vice-L&#237;der do PTB, 1964.</ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Diretor, Servi&#231;o de Atendimento de Menores do Estado do Maranh&#227;o; Diretor-fundador, Servi&#231;o de Assist&#234;ncia a Menores, Maranh&#227;o; M&#233;dico-puericultor, Minist&#233;rio da Sa&#250;de.</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Prim&#225;rio, Col&#233;gio S&#227;o Jos&#233; da Provid&#234;ncia; Secund&#225;rio, Ateneu Teixeira Mendes, S&#227;o Luiz; complementar, Liceu Maranhense; Fac. Nacional de Medicina, Rio de Jeneiro, DF, 1945.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES>C&#194;MARA DOS DEPUTADOS: &#10;MESA: Quarto-Secret&#225;rio, 1958.&#10;COMISS&#213;ES PERMANENTES: Fiscaliza&#231;&#227;o Financeira: Suplente, 1963; Sa&#250;de: Membro, Suplente, 1963; Or&#231;amento: Suplente, 1963, Transportes e Obras P&#250;blicas: Membro.&#10;COMISS&#213;ES ESPECIAIS: Valoriza&#231;&#227;o da Amaz&#244;nia: Membro.</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS>O desenvolvimento psicof&#237;sico da crian&#231;a no seio da fam&#237;l</OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES>Pai - Pedro Pereira</OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1963-1967, BA, PTB. Dt. Posse: 02/02/1963.</MANDATOSCD>
    <MANDATOSEXTERNOS>Prefeito, Ilh&#233;us/BA, Partido: PTB,&#10;Per&#237;odo: 1951 a 1954&#10;Deputado Estadual, BA, Partido: PTB,&#10;Per&#237;odo: 1955 a 1959</MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>122318</CODPESSOA>
    <TXTNOMEPARLAMENTAR>PEDRO CATAL&#195;O</TXTNOMEPARLAMENTAR>
    <TXTNOME>Pedro Vilas Boas Catal&#227;o</TXTNOME>
    <IDECADASTRO>131104</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR>229</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>42</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PTB</SIGPARTIDO>
    <SIGUFREPRESENTACAO>BA</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>22/02/14</DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Ilh&#233;us, BA</NATURALIDADE>
    <PROFISSOES>M&#233;dico Otorrino</PROFISSOES>
    <FILIACAO>Pedro Levino Catal&#227;o e Maria Vilas Boas Catal&#227;o</FILIACAO>
    <CONJUGE>Helena Dias</CONJUGE>
    <FILHOS></FILHOS>
    <LEGISLATURAS>1963-1967</LEGISLATURAS>
    <MANDATOSELETIVOS>Prefeito, 1951-1954, Ilh&#233;us, BA, PTB; Deputado Estadual, 1955-1959, BA, PTB; Deputado Federal, 1963-1967, BA, PTB. Dt. Posse: 02/02/1963.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>PTB; MDB, 1965-.</FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES></SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS></ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Cl&#237;nica Pedro Catala&#231;&#227;o, S&#227;o Paulo.</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Col&#233;gio Ipiranga e Carneiro Ribeiro, Salvador; Otorrinolaringologia, Fac. de Medicina da Bahia, 1933.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES>C&#194;MARAS MUNICIPAIS, ASSEMBL&#201;IAS LEGISLATIVAS E C&#194;MARA LEGISLATIVA DO DF&#10;ALBA: Comiss&#227;o de Sa&#250;de: Titular, 1955-1959.&#10;&#10;C&#194;MARA DOS DEPUTADOS:&#10;COMISS&#213;ES PERMANENTES: Sa&#250;de: Titular; Rela&#231;&#245;es Exteriores: Suplente, membro, 1963.&#10;CPI: Cacau, 1965.</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS>Ioniza&#231;&#227;o no tratamento das supura&#231;&#245;es auriculares.</OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES>Seu irm&#227;o, Eduardo </OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1963-1967, SC, PSD. Dt. Posse: 02/02/1963.</MANDATOSCD>
    <MANDATOSEXTERNOS>Vereador, Blumenau/SC, Partido: PSD,&#10;Per&#237;odo: 1951 a 1959&#10;Deputado Estadual, SC, Partido: PSD,&#10;Per&#237;odo: 1959 a 1963</MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>122319</CODPESSOA>
    <TXTNOMEPARLAMENTAR>PEDRO ZIMMERMANN</TXTNOMEPARLAMENTAR>
    <TXTNOME>Pedro Zimmermann</TXTNOME>
    <IDECADASTRO>131105</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR>230</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>42</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PSD</SIGPARTIDO>
    <SIGUFREPRESENTACAO>SC</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>07/05/19</DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Gaspar, SC</NATURALIDADE>
    <PROFISSOES>Industrial, Advogado e Professor</PROFISSOES>
    <FILIACAO>Pedro Jos&#233; Zimmermann e &#194;ngela Zimmermann</FILIACAO>
    <CONJUGE>Maria Eunice Fontes Zimmermann</CONJUGE>
    <FILHOS>Adriana, Cl&#233;a Maria, Cleonice, Eurico e Jos&#233;</FILHOS>
    <LEGISLATURAS>1963-1967</LEGISLATURAS>
    <MANDATOSELETIVOS>Vereador, 1951-1955 e 1955-1959, Blumenau, SC, PSD; Deputado Estadual, 1959-1963, SC, PSD; Deputado Federal, 1963-1967, SC, PSD. Dt. Posse: 02/02/1963.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>PSD</FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES></SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS></ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Diretor, Companhia Jensen, Agricultura, Ind&#250;stria e Com&#233;rcio, Blumenau, SC; Professor de Economia, Curso b&#225;sico da Escola T&#233;cnica de Com&#233;rico Sena Pereira, SC; Piloto-aviador, For&#231;a A&#233;rea Brasileir</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Col&#233;gio Ser&#225;fico, Rio Negro PR; Direito, Universidade Federal do Paran&#225;, Curitiba.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES>C&#194;MARA DOS DEPUTADOS:&#10;COMISS&#213;ES PERMANENTES: de Economia: Suplente, 1963.</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS>Membro, Conselho T&#233;</CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS>Alemanha, 1966.</MISSOESOFICIAS>
    <OUTRASINFORMACOES>Pai - Pedro Jos&#233; Zi</OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1959-1963, PR, PTB. Dt. Posse: 01/02/1959; Deputado Federal, 1963-1967, PR, PTB. Dt. Posse: 02/02/1963.</MANDATOSCD>
    <MANDATOSEXTERNOS>Prefeito, Ponta Grossa/PR, Partido: N/D,&#10;Per&#237;odo: 1951 a 1954&#10;Deputado Estadual, PR, Partido: UDN,&#10;Per&#237;odo: 1955 a 1959</MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>122320</CODPESSOA>
    <TXTNOMEPARLAMENTAR>PETR&#212;NIO FERNAL</TXTNOMEPARLAMENTAR>
    <TXTNOME>Petr&#244;nio Fernal</TXTNOME>
    <IDECADASTRO>131106</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR>231</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>42</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PTB</SIGPARTIDO>
    <SIGUFREPRESENTACAO>PR</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>08/03/16</DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Oliveira, MG</NATURALIDADE>
    <PROFISSOES>Advogado e Empres&#225;rio</PROFISSOES>
    <FILIACAO>Waldemar Fernal e C&#226;ndida Fernal</FILIACAO>
    <CONJUGE>Hebe Santos Fernal</CONJUGE>
    <FILHOS></FILHOS>
    <LEGISLATURAS>1959-1963 e 1963-1967.</LEGISLATURAS>
    <MANDATOSELETIVOS>Prefeito, 1951-1954, Ponta Grossa, PR, ; Deputado Estadual, 1955-1959, PR, UDN; Deputado Federal, 1959-1963, PR, PTB. Dt. Posse: 01/02/1959; Deputado Federal, 1963-1967, PR, PTB. Dt. Posse: 02/02/1963.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>MDB; PTB</FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES></SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS></ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Auxiliar da Procuradoria da Rep&#250;blica em Belo Horizonte.</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Col&#233;gio S&#227;o Geraldo, MG; Col&#233;gio Arnaldo, MG; Col&#233;gio Afonso Arinos, MG; Fac. de Direito da UFMG, e da USP, 1938.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES>C&#194;MARA DOS DEPUTADOS:&#10;COMISS&#213;ES PERMANENTES: Rela&#231;&#245;es Exteriores: Titular, 1963; Seguran&#231;a Nacional: Suplente, 1963.</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS>Membro, Lions Clube;</ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES></OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1951-1955, MT, PSD. Dt. Posse: 11/03/1951; Deputado Federal, 1959, MT, PSD; Deputado Federal, 1959-1963, MT, PSD. Dt. Posse: 02/02/1959; Deputado Federal, 1963-1967, MT, PSD. Dt. Posse: 02/02/1963.</MANDATOSCD>
    <MANDATOSEXTERNOS></MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>122321</CODPESSOA>
    <TXTNOMEPARLAMENTAR>PHILADELPHO GARCIA</TXTNOMEPARLAMENTAR>
    <TXTNOME>Philadelpho Garcia</TXTNOME>
    <IDECADASTRO>131107</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR>232</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>42</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PSD</SIGPARTIDO>
    <SIGUFREPRESENTACAO>MT</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>25/03/16</DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Coxim, MS</NATURALIDADE>
    <PROFISSOES>Advogado e Funcion&#225;rio P&#250;blico</PROFISSOES>
    <FILIACAO>Francisco Caetano Garcia e Eug&#234;nia de Alves Garcia</FILIACAO>
    <CONJUGE>Eur&#237;dice de Moraes Garcia</CONJUGE>
    <FILHOS>Ana Marta de Moraes Garcia, Filadelfo Garcia J&#250;nior e Jos&#233; Fl&#225;vio Garcia</FILHOS>
    <LEGISLATURAS>1951-1955, 1955-1959, 1959-1963 e 1963-1967.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1951-1955, MT, PSD. Dt. Posse: 11/03/1951; Deputado Federal, -1959, MT, PSD; Deputado Federal, 1959-1963, MT, PSD. Dt. Posse: 02/02/1959; Deputado Federal, 1963-1967, MT, PSD. Dt. Posse: 02/02/1963.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>ARENA; PSD</FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES></SUPLENCIASEFETIVACOES>
    <LICENCAS>Licenciou-se do mandato de Deputado Federal, na Legislatura 1955-1959, para tratar de interesses particulares, de 15 de junho a 11 de novembro de 1955; e para tratamento de sa&#250;de, de 15 de mar&#231;o a 16 de junho, e por 90 dias, a partir de 5 de agosto de 1956.&#10;&#10;Licenciou-se do ma</LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS></ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Policial Civil, Rio de Janeiro, 1935; Investigador de Pol&#237;cia no Distrito Federal; Advogado da Prefeitura do Distrito Federal; Auxiliar de Gabinete de Filinto M&#252;ller, Chefe da Pol&#237;cia do Distrito F</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Instituto S&#227;o Jos&#233;, 1929; Fac. de Direito do Rio de Janeiro, 1936.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES>C&#194;MARA DOS DEPUTADOS:&#10;COMISS&#213;ES PERMANENTES: Legisla&#231;&#227;o Social: Vice-Presidente, Titular, 1963-1964;  Distrito Federal: Suplente, 1963; Diplomacia: Membro.&#10;COMISS&#213;ES EXTERNAS: Para verificar em Mato Grosso a preju&#237;zos causados pelas enchentes do Rio Paraguai: Membro, 1959.&#10;CPI: Fazenda Nacional: Membro, 1963.</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS>Membro da Ordem dos </ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS>Representante da C&#226;</MISSOESOFICIAS>
    <OUTRASINFORMACOES></OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1963 - 1966, PR, PSD. Dt. Posse: 02/02/1963.</MANDATOSCD>
    <MANDATOSEXTERNOS>Prefeito, Curitiba/PR, Partido: N/D,&#10;Per&#237;odo: 1942 a 1945&#10;Vice-Governador, PR, Partido: N/D,&#10;Per&#237;odo: 1966 a 1970</MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>122322</CODPESSOA>
    <TXTNOMEPARLAMENTAR>PL&#205;NIO COSTA</TXTNOMEPARLAMENTAR>
    <TXTNOME>Pl&#237;nio Franco Ferreira da Costa</TXTNOME>
    <IDECADASTRO>131108</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR>233</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>42</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PSD</SIGPARTIDO>
    <SIGUFREPRESENTACAO>PR</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>17/11/20</DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Curitiba, PR</NATURALIDADE>
    <PROFISSOES>Engenheiro Civil</PROFISSOES>
    <FILIACAO>Lysimaco Ferreira da Costa e Esther Franco da Costa</FILIACAO>
    <CONJUGE>Ida Guimar&#227;es da Costa</CONJUGE>
    <FILHOS></FILHOS>
    <LEGISLATURAS>1963-1967</LEGISLATURAS>
    <MANDATOSELETIVOS>Prefeito, 1942-1945, Curitiba, PR, ; Deputado Federal, 1963 - 1966, PR, PSD. Dt. Posse: 02/02/1963; Vice-Governador, 1966-1970, PR, .</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>PSD; ARENA, 1965-.</FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES></SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS>Vice-L&#237;der do PSD, 1963-1965.</ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Fiscal, Inspetoria de Rendas da Prefeitura de Curitiba; Diretor: DER, 1947-1951, 1955-1956 e 1957-1958, Departamento de &#193;guas e Esgotos, 1951-1956, Departamento de &#193;guas e Energia El&#233;trica de Curit</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Escola de Aplica&#231;&#227;o do Instituto de Educa&#231;&#227;o de Curitiba; Instituto Santa Maria; Gin&#225;sio Paranaense; Escola de Engenharia, Univ. Federal do Paran&#225;, 1946.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES>C&#194;MARA DOS DEPUTADOS:&#10;COMISS&#213;ES PERMANENTES: de Transportes e Comunica&#231;&#245;es: Titular, 1963.</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS>Associa&#231;&#227;o Rod. do B</ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS>EEUU, 1966.</MISSOESOFICIAS>
    <OUTRASINFORMACOES>Pai - Lysimaco Cost</OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1955-1956, PR, PSD. Dt. Posse: 12/05/1955; Deputado Federal, 1958-1959, PR, PSD. Dt. Posse: 02/02/1959; Deputado Federal, 1963-1967, PR, PSD. Dt. Posse: 02/02/1963.</MANDATOSCD>
    <MANDATOSEXTERNOS></MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>122323</CODPESSOA>
    <TXTNOMEPARLAMENTAR>RAPHAEL REZENDE</TXTNOMEPARLAMENTAR>
    <TXTNOME>Raphael Ferreira Rezende</TXTNOME>
    <IDECADASTRO>131109</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR>234</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>42</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PSD</SIGPARTIDO>
    <SIGUFREPRESENTACAO>PR</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>04/05/16</DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO></GRAUINSTRUCAO>
    <NATURALIDADE>Lumin&#225;rias, MG</NATURALIDADE>
    <PROFISSOES>Agr&#244;nomo</PROFISSOES>
    <FILIACAO>Jos&#233; Batista Rezende e Diva Ferreira Rezende</FILIACAO>
    <CONJUGE>Ernestina Menicucci Rezende</CONJUGE>
    <FILHOS>Diva Maria Resende, Henrique Menicucci Resende, Luiz S&#233;rgio Menicucci Resende, Raphael Menicucci Resende, Ricardo Menicucci Resende, Vera L&#250;cia Resende e Wilson Menicucci Resende</FILHOS>
    <LEGISLATURAS>1955-1959, 1959-1963 e 1963-1967.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1955-1956, PR, PSD. Dt. Posse: 12/05/1955; Deputado Federal, 1958-1959, PR, PSD. Dt. Posse: 02/02/1959; Deputado Federal, 1963-1967, PR, PSD. Dt. Posse: 02/02/1963.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>PSD; ARENA, 1965-.</FILIACOESPARTIDARIAS>