<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (MANDATOSCD?,MANDATOSEXTERNOS?,NUMGABINETE?,ANEXO?,ANDAR?,TELEFONE?,FAX?,CODPESSOA?,TXTNOMEPARLAMENTAR?,TXTNOME?,IDECADASTRO?,NUMCARTEIRAPARLAMENTAR?,NUMERODAULTIMALEGISLATURA?,SIGPARTIDO?,SIGUFREPRESENTACAO?,DATNASCIMENTO?,NUMCPF?,GRAUINSTRUCAO?,NATURALIDADE?,PROFISSOES?,FILIACAO?,CONJUGE?,FILHOS?,LEGISLATURAS?,MANDATOSELETIVOS?,FILIACOESPARTIDARIAS?,AFASTAMENTOS?,SUPLENCIASEFETIVACOES?,LICENCAS?,PERDASMANDATO?,RENUNCIAS?,ATIVIDADESPARTIDARIAS?,ATIVIDADESPROFISSIONAIS?,ESTUDOSEGRAUSUNIVERSITARIOS?,SEMINARIOS?,ATIVIDADESPARLAMENTARES?,ATIVIDADESSINDICAIS?,CONSELHOS?,CONDECORACOES?,OBRASPUBLICADAS?,MISSOESOFICIAS?,OUTRASINFORMACOES?,FORMATODATANASCIMENTO?)+>
  <!ELEMENT MANDATOSCD (#PCDATA)>
  <!ELEMENT MANDATOSEXTERNOS (#PCDATA)>
  <!ELEMENT NUMGABINETE (#PCDATA)>
  <!ELEMENT ANEXO (#PCDATA)>
  <!ELEMENT ANDAR (#PCDATA)>
  <!ELEMENT TELEFONE (#PCDATA)>
  <!ELEMENT FAX (#PCDATA)>
  <!ELEMENT CODPESSOA (#PCDATA)>
  <!ELEMENT TXTNOMEPARLAMENTAR (#PCDATA)>
  <!ELEMENT TXTNOME (#PCDATA)>
  <!ELEMENT IDECADASTRO (#PCDATA)>
  <!ELEMENT NUMCARTEIRAPARLAMENTAR (#PCDATA)>
  <!ELEMENT NUMERODAULTIMALEGISLATURA (#PCDATA)>
  <!ELEMENT SIGPARTIDO (#PCDATA)>
  <!ELEMENT SIGUFREPRESENTACAO (#PCDATA)>
  <!ELEMENT DATNASCIMENTO (#PCDATA)>
  <!ELEMENT NUMCPF (#PCDATA)>
  <!ELEMENT GRAUINSTRUCAO (#PCDATA)>
  <!ELEMENT NATURALIDADE (#PCDATA)>
  <!ELEMENT PROFISSOES (#PCDATA)>
  <!ELEMENT FILIACAO (#PCDATA)>
  <!ELEMENT CONJUGE (#PCDATA)>
  <!ELEMENT FILHOS (#PCDATA)>
  <!ELEMENT LEGISLATURAS (#PCDATA)>
  <!ELEMENT MANDATOSELETIVOS (#PCDATA)>
  <!ELEMENT FILIACOESPARTIDARIAS (#PCDATA)>
  <!ELEMENT AFASTAMENTOS (#PCDATA)>
  <!ELEMENT SUPLENCIASEFETIVACOES (#PCDATA)>
  <!ELEMENT LICENCAS (#PCDATA)>
  <!ELEMENT PERDASMANDATO (#PCDATA)>
  <!ELEMENT RENUNCIAS (#PCDATA)>
  <!ELEMENT ATIVIDADESPARTIDARIAS (#PCDATA)>
  <!ELEMENT ATIVIDADESPROFISSIONAIS (#PCDATA)>
  <!ELEMENT ESTUDOSEGRAUSUNIVERSITARIOS (#PCDATA)>
  <!ELEMENT SEMINARIOS (#PCDATA)>
  <!ELEMENT ATIVIDADESPARLAMENTARES (#PCDATA)>
  <!ELEMENT ATIVIDADESSINDICAIS (#PCDATA)>
  <!ELEMENT CONSELHOS (#PCDATA)>
  <!ELEMENT CONDECORACOES (#PCDATA)>
  <!ELEMENT OBRASPUBLICADAS (#PCDATA)>
  <!ELEMENT MISSOESOFICIAS (#PCDATA)>
  <!ELEMENT OUTRASINFORMACOES (#PCDATA)>
  <!ELEMENT FORMATODATANASCIMENTO (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 2003-2007, RS, PSDB. Dt. Posse: 18/12/2006; Deputado Federal, 2007-2011, RS, . Dt. Posse: 06/02/2007.</MANDATOSCD>
    <MANDATOSEXTERNOS>Vereador, Rio Grande/RS, Partido: PSDB,&#10;Per&#237;odo: 2000 a 2004&#10;Vereador, Rio Grande/RS, Partido: PSDB,&#10;Per&#237;odo: 2004 a 2006&#10;Prefeito, Rio Grande/RS, Partido: PSDB,&#10;Per&#237;odo: 2006 a 2006</MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>163362</CODPESSOA>
    <TXTNOMEPARLAMENTAR>CL&#193;UDIO DIAZ</TXTNOMEPARLAMENTAR>
    <TXTNOME>Cl&#225;udio Castanheira Diaz</TXTNOME>
    <IDECADASTRO>141057</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR>520</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>53</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PSDB</SIGPARTIDO>
    <SIGUFREPRESENTACAO>RS</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>03/10/53</DATNASCIMENTO>
    <NUMCPF>14632233072</NUMCPF>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Rio Grande, RS</NATURALIDADE>
    <PROFISSOES>Pecuarista e M&#233;dico Veterin&#225;rio</PROFISSOES>
    <FILIACAO>Luis Alberto Diaz e Ledy Castanheira Diaz</FILIACAO>
    <CONJUGE></CONJUGE>
    <FILHOS>Carolina Braga Diaz, Daniela Braga Diaz, Luiza Teixeira Diaz e Marta Teixeira Diaz</FILHOS>
    <LEGISLATURAS>2003-2007 e 2007-2011.</LEGISLATURAS>
    <MANDATOSELETIVOS>Vereador, 1/1/2000-19/12/2006, Rio Grande, RS, PSDB; Deputado Federal, 2003-2007, RS, PSDB. Dt. Posse: 18/12/2006; Vereador, 2004-2006, Rio Grande, , PSDB; Prefeito, 2006, Rio Grande, , PSDB; Deputado Federal, 2007-2011, RS, . Dt. Posse: 06/02/2007.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>PSDB, 1988-.</FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES>Assumiu e foi efetivado como Deputado Federal, na Legislatura 2003-2007, em 20 de dezembro de 2006, na vaga da Deputada Yeda Crusius. &#10;Assumiu, como Suplente, o mandato de Deputado Federal, na Legislatura 2007-2011, em 6 de fevereiro de 2007, sendo efetivado, em 1 de agosto de 2007, na vaga do Dep. J&#250;lio Redecker.</SUPLENCIASEFETIVACOES>
    <LICENCAS>Licenciou-se do mandato de Deputado Federal, na Legislatura 2007-2011, para tratamento de sa&#250;de, por 30 dias, a partir de 25 de agosto de 2009, sem convoca&#231;&#227;o de Suplente; por 30 dias, a partir de 24 de setembro de 2009, sem convoca&#231;&#227;o de Suplente.</LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS>Secret&#225;rio-Geral e Vice-Presidente, Diret&#243;rio do PMDB, 1988;  Secret&#225;rio-Geral, Presidente e Delegado Nacional,  PSDB; 1&#186; Vice-L&#237;der da Minoria, 6/11/2008-1/4/2009; Substituto do L&#237;der da Minoria, 4/3/2009-5/3/2009.</ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS></ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Medicina Veterin&#225;ria, UFPEL, Pelotas, RS, 1981.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES>C&#194;MARA DOS DEPUTADOS - Legislaturas anteriores &#224; 54&#170;&#10;COMISS&#213;ES PERMANENTES: Agricultura, Pecu&#225;ria, Abastecimento Desenvolvimento Rural: Titular, 14/2/2007-6/2/2008, Suplente, 4/3/2008-2/2/2009, 4/3/2009-1/2/2010, 3/3/2010-; Rela&#231;&#245;es Externas e de Defesa Nacional: Suplente, 4/3/2009-16/6/2009; Via&#231;&#227;o e Transportes: 2&#186;  Vice-Presidente, 3/3/2010-, Titular, 4/3/2008-2/2/2009, 4/3/2009-1/2/2010, 3/3/2010-, Suplente, 14/2/2007-6/2/2008.&#10;COMISS&#213;ES ESPECIAIS: PEC n&#186; 272/00, Registro nos Consulados: Titular, 15/5/2007-; PL n&#186; 694/95, Transporte Coletivo Urbano: Suplente, 17/9/2007-; PLP n&#186; 1/07, Limite de Despesa com Pessoal: Suplente, 7/3/2007-.&#10;COMISS&#213;ES EXTERNAS: Situa&#231;&#227;o da Estiagem no RS: Titular, 6/5/2009-.&#10;CPIs: CPI-Sistema Carcer&#225;rio: Suplente, 24/6/2008-8/7/2008;&#10;&#10;C&#194;MARA MUNICIPAL DO RIO GRANDE:&#10;CM- Rio Grande: Mesa: Presidente.&#10;ALRS: Mesa: Presidente, 2004; Comiss&#227;o de Finan&#231;as: Presidente, 2000.&#10;&#10;CONGRESSO NACIONAL&#10;COMISS&#213;ES MISTAS: Conjunta de MERCUSUL: 2&#186; vice-presidente da Representa&#231;&#227;o Brasileira no Parlamento MERCOSUL, onde &#233; coordenador da Comiss&#227;o de Combate a Febre Aftosa, 2007-.</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS>Sindicato dos Leiloeiros Rurais, Rio Grande, RS.</ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES>Mais antigo leiloeiro rural em atividade no Brasil; Foi integrante do MDB Jovem; Implementou o programa Mesa Brasil, em conjunto com o Sistema Fecom&#233;rcio de Rio Grande do Sul, 2006.</OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 2007, PE, PSB. Dt. Posse: 01/01/2007.</MANDATOSCD>
    <MANDATOSEXTERNOS>Deputado Estadual, Recife/PE, Partido: PSB,&#10;Per&#237;odo: 1986 a 2003, Interino&#10;Prefeito, Recife/PE, Partido: PDT,&#10;Per&#237;odo: 1997 a 2003</MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>163821</CODPESSOA>
    <TXTNOMEPARLAMENTAR>CARLOS LAPA</TXTNOMEPARLAMENTAR>
    <TXTNOME>Carlos Adilson Pinto Lapa</TXTNOME>
    <IDECADASTRO>141331</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR>621</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>52</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PSB</SIGPARTIDO>
    <SIGUFREPRESENTACAO>PE</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>07/12/44</DATNASCIMENTO>
    <NUMCPF>03187110444</NUMCPF>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Recife, PE</NATURALIDADE>
    <PROFISSOES>Advogado</PROFISSOES>
    <FILIACAO>Joaquim Pinto Lapa Sobrinho e Zite do Carmo Lapa</FILIACAO>
    <CONJUGE></CONJUGE>
    <FILHOS>Ana Carla Carneiro da Cunha Pinto Lapa Queiroz, Gabriela Carla Carneiro da Cunha Pinto Lapa de Holanda e Regina Carla Carneiro da Cunha Pinto Lapa Pimentel</FILHOS>
    <LEGISLATURAS>2003-2007</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Estadual &#40;Interino&#41;, 1986-2003, PE, PSB; Prefeito, 1997-2003, Recife, PE, PDT; Deputado Federal, 2007, PE, PSB. Dt. Posse: 01/01/2007.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS></FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES>Assumiu e foi efetivado no mandato de Deputado Federal na Legislatura 2003-2007, em 1&#186; de janeiro de 2007, na vaga do Dep Eduardo Campos.</SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS>Membro, Executiva Nacional e Estadual do PSB.</ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Advogado e Auditor Fisca</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Pos-Gradua&#231;&#227;o em Direito Administrativo e Constitucional, Universidade Federal de Pernambuco.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS>IV Congresso Nacion</SEMINARIOS>
    <ATIVIDADESPARLAMENTARES></ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES>Medalha de Honra ao</CONDECORACOES>
    <OBRASPUBLICADAS>Constru&#231;&#227;o da Sede </OBRASPUBLICADAS>
    <MISSOESOFICIAS>Representante da As</MISSOESOFICIAS>
    <OUTRASINFORMACOES></OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 2007, PE, . Dt. Posse: 02/01/2007.</MANDATOSCD>
    <MANDATOSEXTERNOS>Vereador, Recife/PE, Partido: PPB,&#10;Per&#237;odo: 1997 a 2000&#10;Vereador, Recife/PE, Partido: PSB,&#10;Per&#237;odo: 2001 a 2004</MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>163727</CODPESSOA>
    <TXTNOMEPARLAMENTAR>CL&#211;VIS CORR&#202;A</TXTNOMEPARLAMENTAR>
    <TXTNOME>Clovis Corr&#234;a de Oliveira Andrade Filho</TXTNOME>
    <IDECADASTRO>141334</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR>624</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>52</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PSB</SIGPARTIDO>
    <SIGUFREPRESENTACAO>PE</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>06/05/44</DATNASCIMENTO>
    <NUMCPF>01884972420</NUMCPF>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Recife, PE</NATURALIDADE>
    <PROFISSOES>Professor e Desembargador</PROFISSOES>
    <FILIACAO>Cl&#243;vis Corr&#234;a de Oliveira Andrade e Risoleta Corr&#234;a  de Oliveira Andrade</FILIACAO>
    <CONJUGE></CONJUGE>
    <FILHOS>Cla&#250;dia Christina Ara&#250;jo Corr&#234;a de Oliveira Andrade, Cl&#243;vis Corr&#234;a de Oliveira Andrade Neto e Humberto Corr&#234;a de Oliveira Andrada</FILHOS>
    <LEGISLATURAS>2003-2007</LEGISLATURAS>
    <MANDATOSELETIVOS>Vereador, 01/01/1997-31/12/2000, Recife, PE, PPB; Vereador, 01/01/2001-31/12/2004, Recife, PE, PSB; Deputado Federal, 2007, PE, . Dt. Posse: 02/01/2007.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>PPB, 1996-1998; PSDB, 1998-1999; PSB, 1999-2004; PRONA, 2004-.</FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES>Assumiu, como Suplente, o mandato de Deputado Federal na Legislatura 2003-2007, em 2 de janeiro de 2007.</SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS>Presidente Municipal do PSDB, Recife, PE.</ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Chefe, Departamento Jur&#237;</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Bacharel em Direito, Fac. de Direito da Universidade Federal de Pernambuco, 1967; Diplomado pel</ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES>C&#194;MARAS MUNICIPAIS, ASSEMBL&#201;IAS LEGISLATIVAS E C&#194;MARA LEGISLATIVA DO DF:&#10;CM- Recife, PE: Mesa: Vice-Presidente. Comiss&#227;o de Legisla&#231;&#227;o e Justi&#231;a: Presidente.</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS>Presidente, Clube Internacional do Recife.</ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES>Medalha de Comendad</CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES></OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 2003-2007, PA, PT. Dt. Posse: 02/01/2007; Deputado Federal, 2007-2011, PA, PT. Dt. Posse: 01/02/2007; Deputado Federal, 2011-2015, PA, PT. Dt. Posse: 01/02/2011.</MANDATOSCD>
    <MANDATOSEXTERNOS></MANDATOSEXTERNOS>
    <NUMGABINETE>723</NUMGABINETE>
    <ANEXO>4</ANEXO>
    <ANDAR>7</ANDAR>
    <TELEFONE>3215-5723</TELEFONE>
    <FAX>3215-2723</FAX>
    <CODPESSOA>160690</CODPESSOA>
    <TXTNOMEPARLAMENTAR>BETO FARO</TXTNOMEPARLAMENTAR>
    <TXTNOME>Jos&#233; Roberto Oliveira Faro</TXTNOME>
    <IDECADASTRO>141335</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR>19</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>54</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PT</SIGPARTIDO>
    <SIGUFREPRESENTACAO>PA</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>20/06/69</DATNASCIMENTO>
    <NUMCPF>40070565287</NUMCPF>
    <GRAUINSTRUCAO>Secund&#225;rio</GRAUINSTRUCAO>
    <NATURALIDADE>Bujaru, PA</NATURALIDADE>
    <PROFISSOES>Agricultor Familiar</PROFISSOES>
    <FILIACAO>Jos&#233; Jord&#227;o Faro e Laura Oliveira Faro</FILIACAO>
    <CONJUGE></CONJUGE>
    <FILHOS>Yasmin Furtado Faro e Yuri Roberto Furtado Faro</FILHOS>
    <LEGISLATURAS>2003-2007, 2007-2011 e 2011-2015.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 2003-2007, PA, PT. Dt. Posse: 02/01/2007; Deputado Federal, 2007-2011, PA, PT. Dt. Posse: 01/02/2007; Deputado Federal, 2011-2015, PA, PT. Dt. Posse: 01/02/2011.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>PT, 1987-.</FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES>Assumiu, como Suplente, o mandato de Deputado Federal, na Legislatura 2003-2007, em 2 de janeiro de 2007.</SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS>Atividade Partid&#225;ria - C&#226;mara dos Deputados&#10;Vice-L&#237;der, PT, 2008-9/3/2009, 6/4/2011 - 1/2/2013, 4/2/2013-12/3/2013.</ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Superintendente, INCRA, </ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Escola Estadual de Ensino Fundamental D. M&#225;rio de Miranda Villas Boas, Bujaru, PA, 1976-1985.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES>C&#194;MARA DOS DEPUTADOS - 54&#170; Legislatura&#10;COMISS&#195;O PERMANENTE: Comiss&#227;o de Agricultura, Pecu&#225;ria, Abastecimento e Desenvolvimento Rural - CAPADR: Titular,  1/3/2011 - 31/1/2012; Comiss&#227;o de Ci&#234;ncia e Tecnologia, Comunica&#231;&#227;o e Inform&#225;tica - CCTCI: Suplente,  1/3/2011 - 31/1/2012, 7/3/2012 - 2/2/2013; Comiss&#227;o de Agricultura, Pecu&#225;ria, Abastecimento e Desenvolvimento Rural - CAPADR: Titular,  7/3/2012 - 2/2/2013; Comiss&#227;o de Ci&#234;ncia e Tecnologia, Comunica&#231;&#227;o e Inform&#225;tica - CCTCI: Suplente,  5/3/2013 - ; Comiss&#227;o de Agricultura, Pecu&#225;ria, Abastecimento e Desenvolvimento Rural - CAPADR: Titular,  5/3/2013 - .&#10;COMISS&#195;O ESPECIAL: PL 7123/10 - ESTRADA-PARQUE CAMINHO DO COLONO: Titular,  15/9/2011 - ; PEC 037/11 - COMPET&#202;NCIA DA INVESTIGA&#199;&#195;O CRIMINAL: Titular,  4/4/2012 - 25/6/2013; PEC 111/11 - SERVIDORES DOS EX-TERRIT&#211;RIOS: Titular,  9/4/2012 - ; PL 0037/11 - MINERA&#199;&#195;O: Titular,  16/7/2013 - .&#10;&#10;C&#194;MARA DOS DEPUTADOS - Legislaturas anteriores &#224; 54&#170;&#10;COMISS&#213;ES PERMANENTES: Agricultura, Pecu&#225;ria, Abastecimento e Desenvolvimento Rural: 2&#186; Vice-Presidente, 3/3/2010-, Titular, 14/2/2007-6/2/2008, 4/3/2008-2/2/2009, 4/3/2009-1/2/2010, 3/3/2010-; Ci&#234;ncia e Tecnlogia, Comunica&#231;&#227;o e Inform&#225;tica, 4/3/2009-1/2/2010, Suplente, 3/3/2010-; Meio Ambiente e Desenvolvimento Sustent&#225;vel: Suplente, 4/3/2008-2/2/2009; Minas e Energia: Suplente, 14/2/2007-6/2/2008.&#10;COMISS&#213;ES ESPECIAIS: Crise Econ&#244;mico-Financeira - Agricultura: 3&#186; Vice-Presidente, 25/3/2009-, e, Titular, 24/3/2009-; PEC n&#186; 556/02, Seringueiros: Suplente, 4/8/2009-.&#10;CPIs: CPITAELE, Tarifas de Energia El&#233;trica: Suplente, 17/8/2009-18/8/2009.&#10;FRENTES PARLAMENTARES: Quilombos: Membro; Agricultura Familiar: Membro; Via&#231;&#227;o e Transportes: Membro; Ambientalistas: Membro; Igualdade Racial: Membro; Ind&#237;gena: Membro.</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS>Presidente, Sindicato Rural de Bujaru, Bujaru, PA, 1988-1989; Tesoureiro, FETAGRI, Bel&#233;m, PA, 199</ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES></OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 2007, PE, PTB. Dt. Posse: 04/01/2007; Deputado Federal, 2009-2011, PE, . Dt. Posse: 14/04/2009.</MANDATOSCD>
    <MANDATOSEXTERNOS>Vereador, Recife/PE, Partido: PPB,&#10;Per&#237;odo: 2001 a 2004&#10;Vereador, Recife/PE, Partido: PTB,&#10;Per&#237;odo: 2005 a 2005&#10;Vereador, Recife/PE, Partido: PTB,&#10;Per&#237;odo: 2005 a &#10;Vereador, Recife/PE, Partido: PTB,&#10;Per&#237;odo: 2005 a 2005</MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>163759</CODPESSOA>
    <TXTNOMEPARLAMENTAR>CHARLES LUCENA</TXTNOMEPARLAMENTAR>
    <TXTNOME>Ant&#244;nio Charles Lucena de Oliveira M&#233;llo</TXTNOME>
    <IDECADASTRO>141336</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR>587</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>53</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PTB</SIGPARTIDO>
    <SIGUFREPRESENTACAO>PE</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>23/06/67</DATNASCIMENTO>
    <NUMCPF>47837764404</NUMCPF>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Recife, PE</NATURALIDADE>
    <PROFISSOES>M&#233;dico, Empres&#225;rio, Educador e Pol&#237;tico</PROFISSOES>
    <FILIACAO>Ernani Marinho de M&#233;llo e Malba Lucena de OIiveira M&#233;llo</FILIACAO>
    <CONJUGE>Simone Gomes Lucena de M&#233;llo</CONJUGE>
    <FILHOS>Malba Lucena de Oliveira M&#233;llo Neta, Maria Laura Gomes Lucena de M&#233;llo e Maria Loren Gomes Lucena de M&#233;llo</FILHOS>
    <LEGISLATURAS>2003-2007 e 2007-2011.</LEGISLATURAS>
    <MANDATOSELETIVOS>Vereador, 01/01/2001-31/12/2004, Recife, PE, PPB; Deputado Federal, 2007, PE, PTB. Dt. Posse: 04/01/2007; Vereador, 16/11/2005, Recife, PE, PTB; Vereador, 01/01/2005-19/01/2005, Recife, PE, PTB; Vereador, 20/01/2005-15/11/2005, Recife, PE, PTB; Deputado Federal, 2009-2011, PE, . Dt. Posse: 14/04/2009.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>PDT, 1995-1997; PSC, 1997-1999; PPB, 1999-2001; PSDB, 2001-2002; PFL, 2002-2003; PTB, 2003-.</FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES>Assumiu, como Suplente, o mandato de Deputado Federal, na Legislatura 2007-2011, em 14 de abril de 2009, em virtude da efetiva&#231;&#227;o do Deputado Fernando Nascimento, sendo efetivado em 28 de setembro de 2009, em virtude da ren&#250;ncia do Deputado Jos&#233; M&#250;cio Monteiro.</SUPLENCIASEFETIVACOES>
    <LICENCAS>Licenciou-se do mandato de Deputado Federal, na Legislatura 2007-2011, para tratamento de sa&#250;de, por 3 dias, a partir de 12 de maio de 2009; por 2 dias, a partir de 1 de julho de 2009; por 16 dias, de 3 a 18 de agosto de 2009; no dia 14 de abril de 2010; por 7 dias, a partir de 01 de dezembro de 2010; por 3 dias a partir de 10 de dezembro de 2010, sem convoca&#231;&#227;o de suplente.</LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS>Membro, Comiss&#227;o Executiva do Diret&#243;rio Estadual do PSC-PE, 1997;  Membro, Comiss&#227;o Executiva do Diret&#243;rio Municipal Recife do PTB-PE, 2004; Membro do Diret&#243;rio Estadual do PTB-2009.</ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Consultor Administrativo</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Primeiro Grau Menor &#40;1&#170; a 4&#170; S&#233;rie&#41;, Escolas Reunidas Rio Doce, Olinda, PE; Primeiro Grau Maior</ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES>C&#194;MARA DOS DEPUTADOS&#10;COMISS&#213;ES PERMANENTES: Ci&#234;ncia e Tecnologia, Comunica&#231;&#227;o e Inform&#225;tica: Titular, 16/4/2009-1/2/2010; Educa&#231;&#227;o e Cultura: Suplente, 18/8/2009-1/2/2010, 3/3/2010-; Finan&#231;as e Tributa&#231;&#227;o: Titular, 3/3/2010-; Legisla&#231;&#227;o Participativa: Suplente, 3/3/2010-.&#10;COMISS&#213;ES ESPECIAIS: PEC n&#186; 47/03, Alimenta&#231;&#227;o como Direito Social: Suplente, 20/8/2009-4/2/2010; PEC n&#186; 351/09, Regime de Pagamento de Precat&#243;rios: Suplente, 16/9/2009-; PEC n&#186; 391/09, Plano de Carreira Agentes de Sa&#250;de: Suplente, 7/10/2009-4/2/2010; PL n&#186; 2.502/07, Pr&#233;-Sal/ Explora&#231;&#227;o e Produ&#231;&#227;o: Titular, 16/9/2009-; PL n&#186; 7.495/06, Cria Empregos P&#250;blicos na FUNASA: Titular, 5/5/2010-.</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS>Presidente, Conselh</CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES>Filho de Malba Lucena, Educadora Pernambucana que formou 1 Milh&#227;o de pernambucanos nos cursos profissionalizantes; Sua m&#227;e foi Deputada Estadual por duas Legislaturas, 1999-2002 e 2003-2007.</OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 2007-2007, MA, . Dt. Posse: 08/01/2007.</MANDATOSCD>
    <MANDATOSEXTERNOS></MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>163789</CODPESSOA>
    <TXTNOMEPARLAMENTAR>LUIZ ROCHA FILHO</TXTNOMEPARLAMENTAR>
    <TXTNOME>Luiz Rocha Filho</TXTNOME>
    <IDECADASTRO>141337</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR>629</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>52</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PSDB</SIGPARTIDO>
    <SIGUFREPRESENTACAO>MA</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>03/06/64</DATNASCIMENTO>
    <NUMCPF>23794941349</NUMCPF>
    <GRAUINSTRUCAO></GRAUINSTRUCAO>
    <NATURALIDADE>S&#227;o Lu&#237;s, MA</NATURALIDADE>
    <PROFISSOES>Agropecuarista e Advogado</PROFISSOES>
    <FILIACAO>Luiz Alves Coelho Rocha e Terezinha de Jesus Coelho Rocha</FILIACAO>
    <CONJUGE>Marinete Coelho dos Santos</CONJUGE>
    <FILHOS>Fernanda Meneses Rocha, Luciana Meneses Rocha e Luiza Meneses Rocha</FILHOS>
    <LEGISLATURAS>2003-2007</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 2007-2007, MA, . Dt. Posse: 08/01/2007.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>PSDB, 1997-.</FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES>Assumiu e foi efetivado no mandato de Deputado Federal para a Legislatura 2003-2007, em 8 de janeiro de 2007, na vaga do Dep. Jo&#227;o Castelo.</SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS></ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS></ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS></ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES></ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES></OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 2007, SP, PSDB. Dt. Posse: 09/01/2007; Deputado Federal, 2007-2011, SP, PSDB. Dt. Posse: 01/02/2007.</MANDATOSCD>
    <MANDATOSEXTERNOS></MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>162362</CODPESSOA>
    <TXTNOMEPARLAMENTAR>FERNANDO CHUCRE</TXTNOMEPARLAMENTAR>
    <TXTNOME>Fernando Barrancos Chucre</TXTNOME>
    <IDECADASTRO>141344</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR>354</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>53</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PSDB</SIGPARTIDO>
    <SIGUFREPRESENTACAO>SP</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>02/08/66</DATNASCIMENTO>
    <NUMCPF>05809058884</NUMCPF>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Itajub&#225;, MG</NATURALIDADE>
    <PROFISSOES>Empres&#225;rio, Arquiteto e Urbanista</PROFISSOES>
    <FILIACAO>Fuad Gabriel Chucre e Cec&#237;lia Barrancos Chucre</FILIACAO>
    <CONJUGE>Luciane Mota Virg&#237;lio</CONJUGE>
    <FILHOS>Eduardo Virg&#237;lio Chucre e Luiza Virgilio Chucre</FILHOS>
    <LEGISLATURAS>2003-2007 e 2007-2011.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 2007, SP, PSDB. Dt. Posse: 09/01/2007; Deputado Federal, 2007-2011, SP, PSDB. Dt. Posse: 01/02/2007.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>PSDB, 1984-.</FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES>Assumiu, como Suplente, o mandato de Deputado Federal na Legislatura 2003-2007, em 9 de janeiro de 2007.</SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS>Membro, Diret&#243;rio Estadual do PSDB, SP; Coordenador Pol&#237;tico da Grande S&#227;o Paulo Oeste; Presidente, PSDB de  Carapicu&#237;ba, SP, 2003-2005; Membro, Diret&#243;rio Municipal do PSDB de Carapicu&#237;ba, SP.</ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Arquiteto e Urbanista, c</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Pr&#233;-Escolar &#224; 8&#170; s&#233;rie, Escola Estadual de 1&#176; e 2&#176; graus Professor Jos&#233; Maria Rodrigues Leite; </ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS>Pol&#237;ticas de Desenv</SEMINARIOS>
    <ATIVIDADESPARLAMENTARES>C&#194;MARA DOS DEPUTADOS - Legislaturas anteriores &#224; 54&#170;&#10;COMISS&#213;ES PERMANENTES: Desenvolvimento Urbano: Segundo Vice-Presidente, 11/3/2009-3/3/2010, Titular, 14/2/2007-6/2/2008, 4/3/2008-2/2/2009, 4/3/2009-1/2/2010, 3/3/2010-; Turismo e Desporto: Suplente, 5/3/2008-2/2/2009; Via&#231;&#227;o e Transportes: Suplente, 14/2/2007-6/2/2008, 4/3/2008-2/2/2009; 11/3/2009-1/2/2010, 3/3/2010-.&#10;COMISS&#213;ES ESPECIAIS: PEC n&#186; 52/03, Preserva&#231;&#227;o do Ambiente Urbano: Suplente, 4/5/2009-; PEC n&#186; 231/95, Jornada M&#225;xima de Trabalho: Titular, 16/12/2008-; PEC n&#186; 285/08, Fundos Habita&#231;&#227;o de Interesse Social: Titular, 6/8/2009-11/8/2009, e Suplente, 11/8/2009-; PL n&#186; 1/07, Sal&#225;rio M&#237;nimo: Suplente, 7/3/2007-; PL n&#186; 20/07, Parcelamento do Solo para Fins Urbanos: Titular, 1/6/2007-; PL n&#186; 694/95, Transporte Coletivo Urbano: Segundo Vice Presidente, 13/5/2009-, Suplente, 17/9/2007-25/6/2008, Titular, 25/6/2008-; PL n&#186; 1.927/03, Desonera&#231;&#227;o Tribut&#225;ria Transporte: Titular, 11/2/2009-; PL n&#186; 3.460/04, Cria o Estatuto da Metr&#243;pole: Titular, 18/5/2009-.&#10;FRENTE PARLAMENTAR: Mista da Habita&#231;&#227;o; da Habita&#231;&#227;o e Desenvolvimento Urbano; em Defesa das Santas Casas de Miseric&#243;rdias, Hospitais e Entidades Filantr&#243;picas na &#225;rea de Sa&#250;de; de Fortalecimento dos Estados e Munic&#237;pios e Contra a Cria&#231;&#227;o de Novos Estados por Afronta COAstitucional; de Desenvolvimento Vocacional dos Munic&#237;pios; da Inform&#225;tica; em Defesa da Ind&#250;stria Aeron&#225;utica Brasileira; Ambientalista; da Pesca e Aq&#252;icultura.&#10;GRUPOS DE TRABALHO: Consolida&#231;&#227;o da Legisla&#231;&#227;o Brasileira: Suplente, 17/6/2009.</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES></OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 2007-2011, RJ, PL. Dt. Posse: 01/02/2007; Deputado Federal, 2011-2015, RJ, PR. Dt. Posse: 01/02/2011.</MANDATOSCD>
    <MANDATOSEXTERNOS>Vereador, Rio de Janeiro/DF, Partido: PL,&#10;Per&#237;odo: 2005 a 2008</MANDATOSEXTERNOS>
    <NUMGABINETE>926</NUMGABINETE>
    <ANEXO>4</ANEXO>
    <ANDAR>9</ANDAR>
    <TELEFONE>3215-5926</TELEFONE>
    <FAX>3215-2926</FAX>
    <CODPESSOA>160011</CODPESSOA>