<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (MANDATOSCD?,MANDATOSEXTERNOS?,NUMGABINETE?,ANEXO?,ANDAR?,TELEFONE?,FAX?,CODPESSOA?,TXTNOMEPARLAMENTAR?,TXTNOME?,IDECADASTRO?,NUMCARTEIRAPARLAMENTAR?,NUMERODAULTIMALEGISLATURA?,SIGPARTIDO?,SIGUFREPRESENTACAO?,DATNASCIMENTO?,NUMCPF?,GRAUINSTRUCAO?,NATURALIDADE?,PROFISSOES?,FILIACAO?,CONJUGE?,FILHOS?,LEGISLATURAS?,MANDATOSELETIVOS?,FILIACOESPARTIDARIAS?,AFASTAMENTOS?,SUPLENCIASEFETIVACOES?,LICENCAS?,PERDASMANDATO?,RENUNCIAS?,ATIVIDADESPARTIDARIAS?,ATIVIDADESPROFISSIONAIS?,ESTUDOSEGRAUSUNIVERSITARIOS?,SEMINARIOS?,ATIVIDADESPARLAMENTARES?,ATIVIDADESSINDICAIS?,CONSELHOS?,CONDECORACOES?,OBRASPUBLICADAS?,MISSOESOFICIAS?,OUTRASINFORMACOES?,FORMATODATANASCIMENTO?)+>
  <!ELEMENT MANDATOSCD (#PCDATA)>
  <!ELEMENT MANDATOSEXTERNOS (#PCDATA)>
  <!ELEMENT NUMGABINETE (#PCDATA)>
  <!ELEMENT ANEXO (#PCDATA)>
  <!ELEMENT ANDAR (#PCDATA)>
  <!ELEMENT TELEFONE (#PCDATA)>
  <!ELEMENT FAX (#PCDATA)>
  <!ELEMENT CODPESSOA (#PCDATA)>
  <!ELEMENT TXTNOMEPARLAMENTAR (#PCDATA)>
  <!ELEMENT TXTNOME (#PCDATA)>
  <!ELEMENT IDECADASTRO (#PCDATA)>
  <!ELEMENT NUMCARTEIRAPARLAMENTAR (#PCDATA)>
  <!ELEMENT NUMERODAULTIMALEGISLATURA (#PCDATA)>
  <!ELEMENT SIGPARTIDO (#PCDATA)>
  <!ELEMENT SIGUFREPRESENTACAO (#PCDATA)>
  <!ELEMENT DATNASCIMENTO (#PCDATA)>
  <!ELEMENT NUMCPF (#PCDATA)>
  <!ELEMENT GRAUINSTRUCAO (#PCDATA)>
  <!ELEMENT NATURALIDADE (#PCDATA)>
  <!ELEMENT PROFISSOES (#PCDATA)>
  <!ELEMENT FILIACAO (#PCDATA)>
  <!ELEMENT CONJUGE (#PCDATA)>
  <!ELEMENT FILHOS (#PCDATA)>
  <!ELEMENT LEGISLATURAS (#PCDATA)>
  <!ELEMENT MANDATOSELETIVOS (#PCDATA)>
  <!ELEMENT FILIACOESPARTIDARIAS (#PCDATA)>
  <!ELEMENT AFASTAMENTOS (#PCDATA)>
  <!ELEMENT SUPLENCIASEFETIVACOES (#PCDATA)>
  <!ELEMENT LICENCAS (#PCDATA)>
  <!ELEMENT PERDASMANDATO (#PCDATA)>
  <!ELEMENT RENUNCIAS (#PCDATA)>
  <!ELEMENT ATIVIDADESPARTIDARIAS (#PCDATA)>
  <!ELEMENT ATIVIDADESPROFISSIONAIS (#PCDATA)>
  <!ELEMENT ESTUDOSEGRAUSUNIVERSITARIOS (#PCDATA)>
  <!ELEMENT SEMINARIOS (#PCDATA)>
  <!ELEMENT ATIVIDADESPARLAMENTARES (#PCDATA)>
  <!ELEMENT ATIVIDADESSINDICAIS (#PCDATA)>
  <!ELEMENT CONSELHOS (#PCDATA)>
  <!ELEMENT CONDECORACOES (#PCDATA)>
  <!ELEMENT OBRASPUBLICADAS (#PCDATA)>
  <!ELEMENT MISSOESOFICIAS (#PCDATA)>
  <!ELEMENT OUTRASINFORMACOES (#PCDATA)>
  <!ELEMENT FORMATODATANASCIMENTO (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1959-1963, SC, PTB. Dt. Posse: 02/02/1959; Deputado Federal, 1963-1966, SC, PTB. Dt. Posse: 02/02/1963; Deputado Federal, 1989-1991, RJ, PDT. Dt. Posse: 03/01/1989.</MANDATOSCD>
    <MANDATOSEXTERNOS>Vice-Governador, SC, Partido: PTB,&#10;Per&#237;odo: 1961 a 1966</MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>107121</CODPESSOA>
    <TXTNOMEPARLAMENTAR>DOUTEL DE ANDRADE</TXTNOMEPARLAMENTAR>
    <TXTNOME>Armindo Marc&#237;lio Doutel de Andrade</TXTNOME>
    <IDECADASTRO>1539</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR>539</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>48</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PDT</SIGPARTIDO>
    <SIGUFREPRESENTACAO>RJ</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>17/11/20</DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Rio de Janeiro, RJ</NATURALIDADE>
    <PROFISSOES>Advogado, Jornalista e Construtor Civil</PROFISSOES>
    <FILIACAO>Armindo Augusto Doutel de Andrade e C&#226;ndida Margarida Fernandes Andrade</FILIACAO>
    <CONJUGE>L&#237;gia Doutel de Andrade</CONJUGE>
    <FILHOS></FILHOS>
    <LEGISLATURAS>1959-1963, 1963-1967 e 1987-1991.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1959-1963, SC, PTB. Dt. Posse: 02/02/1959; Vice-Governador, 1961-1966, SC, PTB; Deputado Federal, 1963-1966, SC, PTB. Dt. Posse: 02/02/1963; Deputado Federal, 1989-1991, RJ, PDT. Dt. Posse: 03/01/1989.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>PTB, 1952-; MDB, 1966-; PMDB, 1979-1981; PDT, 1981-.</FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES>Assumiu e foi efetivado no mandato de Deputado Federal na legislatura 1987-1991, em 3 de janeiro de 1989, na vaga do Dep. Noel de Carvalho.</SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO>Mandato de Deputado Federal cassado e os direitos pol&#237;ticos suspensos por dez anos, na legislatura 1963-1967, em face do disposto no art. 15 do Ato Institucional n&#186; 2, de 27 de outubro de 1965, expedido pelo Decreto de 13 de outubro de 1966, publicado no D.O. de 14/10/1966, p. 11877.</PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS>Primeiro-Secret&#225;rio do PTB, 1952; Secret&#225;rio-Geral do PTB, 1951 e 1955; Presidente do PTB, SC, 1959; Segundo-Vice-Presidente Nacional do PTB,  1960; Vice-L&#237;der da Maioria, 1962; Vice-L&#237;der do PTB, 1963-1964; L&#237;der do PTB, 1964-1965; L&#237;der da Minoria, 1964; Vice-L&#237;der do MDB, 1965; Vice-Presidente Nacional do PDT, 1981; Presidente Nacional do PDT, 1983-1991.</ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Advogado, Banco do Brasil, 1950; Jornalista, Jornal O Globo, Diretrizes, Di&#225;rio da Noite e O Jornal.</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Prim&#225;rio, Grupo Escolar Rio Grande do Sul, RJ, Secund&#225;rio, Instituto  Lafayette, RJ; Fac. de Direito de S&#227;o Paulo, 1943.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES></ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS>Observador Parlamentar, 26&#170; Confer&#234;ncia Internacional de Instru&#231;&#227;o P&#250;blica, Genebra, 1963.</MISSOESOFICIAS>
    <OUTRASINFORMACOES>Seu pai era natural de Portugal, e foi jornalista; Esposa - L&#237;gia Doutel de Andrade, Deputada Federal, MDB, 1967-1968, filha de Jos&#233; da Costa Moelmamm, Engenheiro, Prefeito de Florian&#243;polis, e Secret&#225;rio da Fazenda de Santa Catarina.</OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1983-1987, MS, PMDB. Dt. Posse: 01/02/1983; Deputado Federal &#40;Constituinte&#41;, 1987-1991, MS, PMDB. Dt. Posse: 01/02/1987.</MANDATOSCD>
    <MANDATOSEXTERNOS>Vereador, Campo Grande/MS, Partido: UDN,&#10;Per&#237;odo: 1963 a 1966&#10;Prefeito, Campo Grande/MS, Partido: MDB,&#10;Per&#237;odo: 1967 a 1969&#10;Vereador, Campo Grande/MS, Partido: MDB,&#10;Per&#237;odo: 1977 a 1983</MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>105982</CODPESSOA>
    <TXTNOMEPARLAMENTAR>PL&#205;NIO MARTINS</TXTNOMEPARLAMENTAR>
    <TXTNOME>Pl&#237;nio Barbosa Martins</TXTNOME>
    <IDECADASTRO>1536</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR>423</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>48</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PSDB</SIGPARTIDO>
    <SIGUFREPRESENTACAO>MS</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>16/09/26</DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Campo Grande, MS</NATURALIDADE>
    <PROFISSOES>Advogado</PROFISSOES>
    <FILIACAO>Henrique Martins&#10; e Adelaide Barbosa Martins</FILIACAO>
    <CONJUGE>Ruth Martins</CONJUGE>
    <FILHOS></FILHOS>
    <LEGISLATURAS>1983-1987 e 1987-1991.</LEGISLATURAS>
    <MANDATOSELETIVOS>Vereador, 1963-1966, Campo Grande, MT, UDN; Prefeito, 1967-1969, Campo Grande, MT, MDB; Vereador, 1977-1983, Campo Grande, MT, MDB; Deputado Federal, 1983-1987, MS, PMDB. Dt. Posse: 01/02/1983; Deputado Federal &#40;Constituinte&#41;, 1987-1991, MS, PMDB. Dt. Posse: 01/02/1987.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>UDN, 1962-1966; MDB, 1966-1979; PMDB, 1980-.</FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES></SUPLENCIASEFETIVACOES>
    <LICENCAS>Licenciou-se do man</LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS>Membro da Executiva Nacional do PMDB, 1983.</ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Auditor Militar campo Grande, MT, 1972; Professor de Direito Civil, Faculdade de Direito de Campo Grande, 1975-1979.</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Direito, PUC, S&#227;o Paulo, 1950.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES>ASSEMBLEIA NACIONAL CONS</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS>Visita aos Estados Unidos da Am&#233;rica, a convite do Departamento de Estado, 1969. Membro, Comiss&#227;o representante da C&#226;mara dos Deputados, nas solenidades comemorativas do anivers&#225;rio</MISSOESOFICIAS>
    <OUTRASINFORMACOES>Seu tio, Vespasiano Barbosa Martins participou da resolu&#231;&#227;o de 1930, foi senador por Mato Grosso entre 1935 e 1937, constituinte de 1946 e novamente senador entre 1946 a 1955. Seu irm&#227;o, Wilson Martins, foi deputado federal por Mato Grosso entre 1963 e 1969, governador de Mato Grosso do Sul de 1983 a 1986 e em 1995 e senador entre 1988 e 1994.</OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal &#40;Constituinte&#41;, 1987-1991, MS, PFL. Dt. Posse: 01/02/1987.</MANDATOSCD>
    <MANDATOSEXTERNOS>Deputado Estadual, MS, Partido: PDS,&#10;Per&#237;odo: 1982 a 1985&#10;Deputado Estadual, MS, Partido: PFL,&#10;Per&#237;odo: 1985 a 1987</MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>106222</CODPESSOA>
    <TXTNOMEPARLAMENTAR>GANDI JAMIL</TXTNOMEPARLAMENTAR>
    <TXTNOME>Gandi Jamil Georges</TXTNOME>
    <IDECADASTRO>1537</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR></NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>48</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PFL</SIGPARTIDO>
    <SIGUFREPRESENTACAO>MS</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>03/03/56</DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO>Secund&#225;rio</GRAUINSTRUCAO>
    <NATURALIDADE>Ponta Por&#227;, MS</NATURALIDADE>
    <PROFISSOES>Agropecuarista, Industrial e Comerciante</PROFISSOES>
    <FILIACAO>Jamil Georges&#10; e Zine Georges</FILIACAO>
    <CONJUGE>Ana Karla Zahran Georges</CONJUGE>
    <FILHOS></FILHOS>
    <LEGISLATURAS>1987-1991</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Estadual, 1982-1985, MS, PDS; Deputado Estadual, 1985-1987, MS, PFL; Deputado Federal &#40;Constituinte&#41;, 1987-1991, MS, PFL. Dt. Posse: 01/02/1987.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>PDS, 1982-1985; PFL, 1985-.</FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES></SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS>Presidente da Juventude do Partido Democr&#225;tico Social, JDS, Ponta Por&#227;, MS, 1982-1983; Delegado &#224; Conven&#231;&#227;o Nacional do PDS, 1984; Presidente do PFL/MS, 1988-1989.</ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS></ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Segundo Grau, Col&#233;gio Objetivo, S&#227;o Paulo; Direito, &#40;incomp.&#41;, Fac. de Direito, Mogi da Cruzes,</ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES>C&#194;MARA DOS DEPUTADOS:&#10;Pr</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES></OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal &#40;Constituinte&#41;, 1988, MS, PMDB. Dt. Posse: 06/09/1988.</MANDATOSCD>
    <MANDATOSEXTERNOS>Prefeito, Corumb&#225;/MS, Partido: PMDB,&#10;Per&#237;odo: 1984 a 1985</MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>104264</CODPESSOA>
    <TXTNOMEPARLAMENTAR>FADAH GATTASS</TXTNOMEPARLAMENTAR>
    <TXTNOME>Fadah Scaff Gattass</TXTNOME>
    <IDECADASTRO>1507</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR></NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>48</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PMDB</SIGPARTIDO>
    <SIGUFREPRESENTACAO>MS</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>10/02/21</DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Corumb&#225;, MS</NATURALIDADE>
    <PROFISSOES>M&#233;dico e Pecuarista</PROFISSOES>
    <FILIACAO>Miguel Abdala Gattass Orro&#10; e Sofia Scaff</FILIACAO>
    <CONJUGE>Luiza Carmem G. de Oliveira Gattass</CONJUGE>
    <FILHOS></FILHOS>
    <LEGISLATURAS>1987-1991</LEGISLATURAS>
    <MANDATOSELETIVOS>Prefeito, 1984-1985, Corumb&#225;, MS, PMDB; Deputado Federal &#40;Constituinte&#41;, 1988, MS, PMDB. Dt. Posse: 06/09/1988.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>PMDB; PSD, 1948-1964.</FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES>Assumiu, como Suplente, o mandato de Deputado Federal Constituinte, em 6 a 27 de setembro de 1988, na vaga do Deputado Ruben Figueir&#243;.</SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS></ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>M&#233;dico Sanitarista, lotado no Servi&#231;o de Sa&#250;de dos Portos e Aeroportos de Fronteira, 1951-1981; prestou servi&#231;os como M&#233;dico &#224; comunidade corumbaense e ladarense no IAPETEC, posteriormente transformado</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Medicina, Univ. do Brasil, Rio de Janeiro, 1945; concluiu Cursos T&#233;cnicos e de Especializa&#231;&#227;o.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES>C&#194;MARA DOS DEPUTADOS:&#10;CO</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS>Presidente da Associ</ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES>T&#237;tulo de Amigo da </CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES></OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 03/01/1989-31/01/1991, SE, PMDB.</MANDATOSCD>
    <MANDATOSEXTERNOS>Vereador, Est&#226;ncia/SE, Partido: UDN,&#10;Per&#237;odo: 1963 a 1967&#10;Deputado Estadual, SE, Partido: MDB,&#10;Per&#237;odo: 1975 a 1979&#10;Deputado Estadual, SE, Partido: MDB,&#10;Per&#237;odo: 1979 a 1983&#10;Deputado Estadual, SE, Partido: PMDB,&#10;Per&#237;odo: 1983 a 1987</MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>104299</CODPESSOA>
    <TXTNOMEPARLAMENTAR>LEOPOLDO SOUZA</TXTNOMEPARLAMENTAR>
    <TXTNOME>Leopoldo de Araujo Souza Neto</TXTNOME>
    <IDECADASTRO>1513</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR></NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>48</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PMDB</SIGPARTIDO>
    <SIGUFREPRESENTACAO>SE</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>03/02/38</DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Est&#226;ncia, SE</NATURALIDADE>
    <PROFISSOES>Tabeli&#227;o</PROFISSOES>
    <FILIACAO>Raymundo Silveira Souza&#10; e Doralice Fontes Souza</FILIACAO>
    <CONJUGE>Arlinda Maria Lemos</CONJUGE>
    <FILHOS></FILHOS>
    <LEGISLATURAS>1987-1991</LEGISLATURAS>
    <MANDATOSELETIVOS>Vereador, 1963-1967, Est&#226;ncia, SE, UDN; Deputado Estadual, 1975-1979, SE, MDB; Deputado Estadual, 1979-1983, SE, MDB; Deputado Estadual, 1983-1987, SE, PMDB; Deputado Federal, 03/01/1989-31/01/1991, SE, PMDB.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>UDN, 1962-1966; MDB, 1966-1979; PMDB, 1980-; PT, 1997-.</FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES>Assumiu e foi efetivado, no mandato de Deputado Estadual para a legislatura 1987-1991, em 3 de janeiro de1989, na vaga do Dep. Ant&#244;nio Carlos Franco.</SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS>L&#237;der, ALSE/MDB, 1976-1978; L&#237;der, ALSE/PMDB, 1981-1982.</ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Tabeli&#227;o de Notas, Est&#226;ncia/SE, 1958.</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Direito, UFS Aracaju, 1974.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES>ALSE: Comiss&#245;es: Membro,</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS>Membro Efetivo da Se</ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES>Comenda Jubileu de </CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES>Representante da Assembl&#233;ia Legislativa de Sergipe na Promulga&#231;&#227;o das Constitui&#231;&#245;es Estaduais de Mato Grosso do Sul e Rond&#244;nia.</OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1989-1991, MG, PMDB. Dt. Posse: 03/01/1989.</MANDATOSCD>
    <MANDATOSEXTERNOS></MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>104315</CODPESSOA>
    <TXTNOMEPARLAMENTAR>PAULO MENICUCCI</TXTNOMEPARLAMENTAR>
    <TXTNOME>Paulo Roberto Menicucci</TXTNOME>
    <IDECADASTRO>1515</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR></NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>48</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PMDB</SIGPARTIDO>
    <SIGUFREPRESENTACAO>MG</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>24/12/44</DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO></GRAUINSTRUCAO>
    <NATURALIDADE>Lavras, MG</NATURALIDADE>
    <PROFISSOES></PROFISSOES>
    <FILIACAO>Silvio Menicucci&#10; e Nerina Menicucci</FILIACAO>
    <CONJUGE></CONJUGE>
    <FILHOS></FILHOS>
    <LEGISLATURAS>1987-1991</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1989-1991, MG, PMDB. Dt. Posse: 03/01/1989.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS></FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES>Exerceu, como Suplente, o mandato Deputado Federal para a legislatura 1987-1991, de 3 a 15 de janeiro de1989, na vaga do Deputado Leopoldo Bessone.</SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS></ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS></ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS></ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES></ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES>Eleito Suplente de Deputado Federal, exerceu o mandato de 3 a 17 de janeiro de1989.</OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1989, MS, PMDB. Dt. Posse: 03/01/1989.</MANDATOSCD>
    <MANDATOSEXTERNOS></MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>104330</CODPESSOA>
    <TXTNOMEPARLAMENTAR>ABDALLA JALLAD</TXTNOMEPARLAMENTAR>
    <TXTNOME>Abdalla Jallad</TXTNOME>
    <IDECADASTRO>1516</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR></NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>48</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PMDB</SIGPARTIDO>
    <SIGUFREPRESENTACAO>MS</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>09/12/40</DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Corumb&#225;, MS</NATURALIDADE>
    <PROFISSOES>Advogado</PROFISSOES>
    <FILIACAO>Fuad Jallad&#10; e Neri Buainain Jallad</FILIACAO>
    <CONJUGE>Celina Martins Jallad</CONJUGE>
    <FILHOS></FILHOS>
    <LEGISLATURAS>1987-1991</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1989, MS, PMDB. Dt. Posse: 03/01/1989.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>PMDB</FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES>Exerceu, como Suplente, o mandato de Deputado Federal para a legislatura 1987-1991, de 3 de janeiro a 3 de fevereiro de 1989, na vaga do Dep. Ruben Figuereiro.</SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS></ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Subchefe da Casa Civil, Campo Grande, MS, 1983-1986.</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Direito, UFPR, Curitiba, 1962-1966.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES></ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES></OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1989-1991, PB, PSB. Dt. Posse: 03/01/1989.</MANDATOSCD>
    <MANDATOSEXTERNOS>Vereador, Cajazeiras/PB, Partido: PSD,&#10;Per&#237;odo: 1959 a 1963&#10;Vereador, Cajazeiras/PB, Partido: UDN,&#10;Per&#237;odo: 1963 a 1969&#10;Vereador, Cajazeiras/PB, Partido: ARENA,&#10;Per&#237;odo: 1977 a 1983</MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>104337</CODPESSOA>
    <TXTNOMEPARLAMENTAR>FRANCISCO ROLIM</TXTNOMEPARLAMENTAR>
    <TXTNOME>Francisco Matias Rolim</TXTNOME>
    <IDECADASTRO>1517</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR></NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>48</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PSB</SIGPARTIDO>
    <SIGUFREPRESENTACAO>PB</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>06/12/22</DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO>Secund&#225;rio</GRAUINSTRUCAO>
    <NATURALIDADE>Umari, CE</NATURALIDADE>
    <PROFISSOES>Agropecuarista, Industrial e Comerciante</PROFISSOES>
    <FILIACAO>Matias Duarte Passos&#10; e Angelina Duarte Rolim</FILIACAO>
    <CONJUGE>Tereza Augusta Rolim</CONJUGE>
    <FILHOS></FILHOS>
    <LEGISLATURAS>1987-1991</LEGISLATURAS>
    <MANDATOSELETIVOS>Vereador, 1959-1963, Cajazeiras, PB, PSD; Vereador, 1963-1969, Cajazeiras, PB, UDN; Vereador, 1977-1983, Cajazeiras, PB, ARENA; Deputado Federal, 1989-1991, PB, PSB. Dt. Posse: 03/01/1989.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>PSD, 1950-1962; UDN, 1963-1967; ARENA, 1967-; PMDB, 1986-1988; PDS, 1986-; PSB, 1988-.</FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES>Assumiu, como Suplente, o mandato de Deputado Federal para a legislatura 1987-1991, em 3 de janeiro de1989, sendo efetivado.</SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS></ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS></ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS></ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES>Presidente, C&#226;mara Munic</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS>Do miolo do sert&#227;o.</OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES></OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1989-1991, TO, PFL. Dt. Posse: 09/01/1989.</MANDATOSCD>
    <MANDATOSEXTERNOS>Prefeito, Tocantin&#243;polis/GO, Partido: N/D,&#10;Per&#237;odo: 1960 a 1965&#10;Deputado Estadual, GO, Partido: ARENA,&#10;Per&#237;odo: 1975 a 1979&#10;Deputado Estadual, GO, Partido: ARENA,&#10;Per&#237;odo: 1979 a 1983</MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>104359</CODPESSOA>
    <TXTNOMEPARLAMENTAR>ALZIRO GOMES</TXTNOMEPARLAMENTAR>
    <TXTNOME>Alziro Gomes de Souza</TXTNOME>
    <IDECADASTRO>1519</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR></NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>48</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PFL</SIGPARTIDO>
    <SIGUFREPRESENTACAO>TO</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>10/07/23</DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO>Secund&#225;rio</GRAUINSTRUCAO>
    <NATURALIDADE>Imperatriz, MA</NATURALIDADE>
    <PROFISSOES>Empres&#225;rio e Fazendeiro</PROFISSOES>
    <FILIACAO>Antonio Greg&#243;rio de Souza&#10; e Temotea Gomes de Souza</FILIACAO>
    <CONJUGE>Iolete da Ascen&#231;&#227;o Barros de Souza</CONJUGE>
    <FILHOS></FILHOS>
    <LEGISLATURAS>1987-1991</LEGISLATURAS>
    <MANDATOSELETIVOS>Prefeito, 1960-1965, Tocantin&#243;polis, GO, ; Deputado Estadual, 1975-1979, GO, ARENA; Deputado Estadual, 1979-1983, GO, ARENA; Deputado Federal, 1989-1991, TO, PFL. Dt. Posse: 09/01/1989.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>PFL; ARENA, 1975-1979.</FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES>Assumiu, como Suplente, o mandato de Deputado Federal para a legislatura 1987-1991, de  9 de janeiro de1989 a 8 de janeiro de 1990, na vaga do Dep. Leomar Quintanilha.</SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS></ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Ind&#250;stria de Gipsita</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Contabilidade, Col&#233;gio Marista, S&#227;o Lu&#237;s, 1943-1948.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES>Segundo-Vice-Presidente,</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES>Endere&#231;os e telefones retirados do SIGESP-DEP.</OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1979-1983, CE, MDB. Dt. Posse: 01/02/1979; Deputado Federal, 1983-1987, CE, PMDB. Dt. Posse: 24/03/1983; Deputado Federal, 1988-1989, CE, PMDB. Dt. Posse: 07/12/1988.</MANDATOSCD>
    <MANDATOSEXTERNOS>Deputado Estadual, CE, Partido: MDB,&#10;Per&#237;odo: 1967 a 1971&#10;Deputado Estadual, CE, Partido: MDB,&#10;Per&#237;odo: 1971 a 1975</MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>104382</CODPESSOA>
    <TXTNOMEPARLAMENTAR>IRANILDO PEREIRA</TXTNOMEPARLAMENTAR>
    <TXTNOME>Iranildo Pereira de Oliveira</TXTNOME>
    <IDECADASTRO>1521</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR></NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>48</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PFL</SIGPARTIDO>
    <SIGUFREPRESENTACAO>CE</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>19/12/37</DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Santana do Cariri, CE</NATURALIDADE>
    <PROFISSOES>Agropecuarista, Advogado e Industrial Armador</PROFISSOES>
    <FILIACAO>Antonio Pereira de Oliveira&#10; e Ad&#225;lia Pereira E Silva</FILIACAO>
    <CONJUGE>Maria do Carmo Melo de Oliveira</CONJUGE>
    <FILHOS></FILHOS>
    <LEGISLATURAS>1979-1983, 1983-1987 e 1987-1991.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Estadual, 1967-1971, CE, MDB; Deputado Estadual, 1971-1975, CE, MDB; Deputado Federal, 1979-1983, CE, MDB. Dt. Posse: 01/02/1979; Deputado Federal, 1983-1987, CE, PMDB. Dt. Posse: 24/03/1983; Deputado Federal, 1988-1989, CE, PMDB. Dt. Posse: 07/12/1988.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>MDB, 1966-1979; PMDB, 1980-.</FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES>Assumiu, como Suplente, o mandato  de Deputado Federal, de 24 de mar&#231;o a 6 de agosto de 1983; de 15 de agosto a 14 de setembro de 1983; Assumiu, como Suplente, o mandato Deputado Federal, de 7 de dezembro de 1988 a 10 de abril de 1989.</SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS>Vice-L&#237;der: CD&#92; PMDB, 1982.</ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS></ATIVIDADESPROFISSIONAIS>