<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (MANDATOSCD?,MANDATOSEXTERNOS?,NUMGABINETE?,ANEXO?,ANDAR?,TELEFONE?,FAX?,CODPESSOA?,TXTNOMEPARLAMENTAR?,TXTNOME?,IDECADASTRO?,NUMCARTEIRAPARLAMENTAR?,NUMERODAULTIMALEGISLATURA?,SIGPARTIDO?,SIGUFREPRESENTACAO?,DATNASCIMENTO?,NUMCPF?,GRAUINSTRUCAO?,NATURALIDADE?,PROFISSOES?,FILIACAO?,CONJUGE?,FILHOS?,LEGISLATURAS?,MANDATOSELETIVOS?,FILIACOESPARTIDARIAS?,AFASTAMENTOS?,SUPLENCIASEFETIVACOES?,LICENCAS?,PERDASMANDATO?,RENUNCIAS?,ATIVIDADESPARTIDARIAS?,ATIVIDADESPROFISSIONAIS?,ESTUDOSEGRAUSUNIVERSITARIOS?,SEMINARIOS?,ATIVIDADESPARLAMENTARES?,ATIVIDADESSINDICAIS?,CONSELHOS?,CONDECORACOES?,OBRASPUBLICADAS?,MISSOESOFICIAS?,OUTRASINFORMACOES?,FORMATODATANASCIMENTO?)+>
  <!ELEMENT MANDATOSCD (#PCDATA)>
  <!ELEMENT MANDATOSEXTERNOS (#PCDATA)>
  <!ELEMENT NUMGABINETE (#PCDATA)>
  <!ELEMENT ANEXO (#PCDATA)>
  <!ELEMENT ANDAR (#PCDATA)>
  <!ELEMENT TELEFONE (#PCDATA)>
  <!ELEMENT FAX (#PCDATA)>
  <!ELEMENT CODPESSOA (#PCDATA)>
  <!ELEMENT TXTNOMEPARLAMENTAR (#PCDATA)>
  <!ELEMENT TXTNOME (#PCDATA)>
  <!ELEMENT IDECADASTRO (#PCDATA)>
  <!ELEMENT NUMCARTEIRAPARLAMENTAR (#PCDATA)>
  <!ELEMENT NUMERODAULTIMALEGISLATURA (#PCDATA)>
  <!ELEMENT SIGPARTIDO (#PCDATA)>
  <!ELEMENT SIGUFREPRESENTACAO (#PCDATA)>
  <!ELEMENT DATNASCIMENTO (#PCDATA)>
  <!ELEMENT NUMCPF (#PCDATA)>
  <!ELEMENT GRAUINSTRUCAO (#PCDATA)>
  <!ELEMENT NATURALIDADE (#PCDATA)>
  <!ELEMENT PROFISSOES (#PCDATA)>
  <!ELEMENT FILIACAO (#PCDATA)>
  <!ELEMENT CONJUGE (#PCDATA)>
  <!ELEMENT FILHOS (#PCDATA)>
  <!ELEMENT LEGISLATURAS (#PCDATA)>
  <!ELEMENT MANDATOSELETIVOS (#PCDATA)>
  <!ELEMENT FILIACOESPARTIDARIAS (#PCDATA)>
  <!ELEMENT AFASTAMENTOS (#PCDATA)>
  <!ELEMENT SUPLENCIASEFETIVACOES (#PCDATA)>
  <!ELEMENT LICENCAS (#PCDATA)>
  <!ELEMENT PERDASMANDATO (#PCDATA)>
  <!ELEMENT RENUNCIAS (#PCDATA)>
  <!ELEMENT ATIVIDADESPARTIDARIAS (#PCDATA)>
  <!ELEMENT ATIVIDADESPROFISSIONAIS (#PCDATA)>
  <!ELEMENT ESTUDOSEGRAUSUNIVERSITARIOS (#PCDATA)>
  <!ELEMENT SEMINARIOS (#PCDATA)>
  <!ELEMENT ATIVIDADESPARLAMENTARES (#PCDATA)>
  <!ELEMENT ATIVIDADESSINDICAIS (#PCDATA)>
  <!ELEMENT CONSELHOS (#PCDATA)>
  <!ELEMENT CONDECORACOES (#PCDATA)>
  <!ELEMENT OBRASPUBLICADAS (#PCDATA)>
  <!ELEMENT MISSOESOFICIAS (#PCDATA)>
  <!ELEMENT OUTRASINFORMACOES (#PCDATA)>
  <!ELEMENT FORMATODATANASCIMENTO (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1984-1987, MG, PDS. Dt. Posse: 09/04/1984.</MANDATOSCD>
    <MANDATOSEXTERNOS>Deputado Estadual, N&#227;o informado/MG, Partido: N/D,&#10;Per&#237;odo: 1967 a 1970&#10;Deputado Estadual, N&#227;o informado/MG, Partido: N/D,&#10;Per&#237;odo: 1975 a 1978&#10;Deputado Estadual, N&#227;o informado/MG, Partido: N/D,&#10;Per&#237;odo: 1979 a 1982&#10;Vereador, Oliveira/MG, Partido: N/D,&#10;Per&#237;odo:  a</MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>123127</CODPESSOA>
    <TXTNOMEPARLAMENTAR>EM&#205;LIO HADDAD</TXTNOMEPARLAMENTAR>
    <TXTNOME>Em&#237;lio Haddah Filho</TXTNOME>
    <IDECADASTRO>131901</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR></NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>47</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PMDB</SIGPARTIDO>
    <SIGUFREPRESENTACAO>MG</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>06/04/38</DATNASCIMENTO>
    <NUMCPF>00408727691</NUMCPF>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Oliveira, MG</NATURALIDADE>
    <PROFISSOES>Advogado</PROFISSOES>
    <FILIACAO>Em&#237;lio Haddah e Lile Miguel Haddah</FILIACAO>
    <CONJUGE>Maria Em&#237;lia Mitre Haddah</CONJUGE>
    <FILHOS>Em&#237;lio Haddah Neto e Michel Mitre Haddad</FILHOS>
    <LEGISLATURAS>1983-1987</LEGISLATURAS>
    <MANDATOSELETIVOS>Vereador, , Oliveira, MG, ; Deputado Estadual, 1967-1970, MG, ; Deputado Estadual, 1975-1978, MG, ; Deputado Estadual, 1979-1982, MG, ; Deputado Federal, 1984-1987, MG, PDS. Dt. Posse: 09/04/1984.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>UDN; PFL; MDB</FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES>Assumiu, como Suplente, o mandato de Deputado Federal, na Legislatura de 1983-987, em 09 de abril de 1984, em virtude do falecimento do Deputado Ozanan Coelho.</SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS></ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Escrit&#243;rio de Advocacia em Oliveira, MG; Escrit&#243;rio em Belo Horizonte, MG; Professor de Ensino M&#233;dio em diversos col&#233;gios, em Belo Horizonte e Oliveira, MG; Presidente da Pra&#231;a de Esportes do Oliveira T&#234;nis Clube; Vice Presidente do Diret&#243;rio Acad&#234;mico Eug&#234;nio Pacelli, Fac. Mineira de Direito, Universidade Cat&#243;lica de Minas Gerais, 1959; Presidente do mesmo Diret&#243;rio, 1960; Diretor do Lions Clube de Oliveira; Diretor do Social Futebol Clube; Oliveira, MG; Diretor do Esporte Clube Fabril, Oliveira, MG; Diretor do Catigu&#225; Campestre Clube, Oliveira, MG.</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>At&#233; 3o Prim&#225;rio, Escola Estadual Francisco Fernandes, Oliveira, MG; 4o ano, Escola Estadual L&#250;cio dos Santos, Belo Horizonte, MG; Ginasial, Col&#233;gio T&#233;cnica de Com&#233;rcio de Belo Horizonte, MG; Direito, Fac. Mineira de Direito, Universidade Cat&#243;lica de Minas Gerais, MG, 1962.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES>ALMG - Constituinte: Comiss&#227;o Executiva da Assembl&#233;ia: Quarta secretaria, 1968; Comiss&#227;o de Educa&#231;&#227;o e Cultura: Vice-Presidente, 1969; Constitui&#231;&#227;o, Legisla&#231;&#227;o e Justi&#231;a, 1970; Comiss&#227;o de Reda&#231;&#227;o: Membro, 1970.</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES>Medalha Santos Dumont, MG, 1975; Grande Medalha da Inconfid&#234;ncia, MG, 1975; Medalha do M&#233;rito Legislativo, MG, 1984.</CONDECORACOES>
    <OBRASPUBLICADAS>HADDAH, Em&#237;lio. Subs&#237;dios para an&#225;lise dos problemas das pequenas e m&#233;dias empresas. MG, 1968.</OBRASPUBLICADAS>
    <MISSOESOFICIAS>Membro, Miss&#227;o Cultural no Exterior, Damasco, S&#237;ria, 1985.</MISSOESOFICIAS>
    <OUTRASINFORMACOES></OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1979-1983, RS, PDS. Dt. Posse: 01/02/1979; Deputado Federal, 1983-1987, RS, PDS. Dt. Posse: 01/02/1983.</MANDATOSCD>
    <MANDATOSEXTERNOS>Vereador, Iju&#237;/RS, Partido: N/D,&#10;Per&#237;odo: 1963 a 1969&#10;Prefeito, Iju&#237;/RS, Partido: ARENA,&#10;Per&#237;odo: 1973 a 1976</MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>123128</CODPESSOA>
    <TXTNOMEPARLAMENTAR>EM&#205;DIO PERONDI</TXTNOMEPARLAMENTAR>
    <TXTNOME>Em&#237;dio Odosio Perondi</TXTNOME>
    <IDECADASTRO>131902</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR></NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>47</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PDS</SIGPARTIDO>
    <SIGUFREPRESENTACAO>RS</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>05/09/38</DATNASCIMENTO>
    <NUMCPF>01300920025</NUMCPF>
    <GRAUINSTRUCAO>Secund&#225;rio</GRAUINSTRUCAO>
    <NATURALIDADE>Tupanciret&#227;, RS</NATURALIDADE>
    <PROFISSOES>Agricultor, Industrial e Comerciante</PROFISSOES>
    <FILIACAO>Jo&#227;o Perondi e Antonia Zardin Perondi</FILIACAO>
    <CONJUGE>Helianita Gressler Perondi</CONJUGE>
    <FILHOS>Fabiana Perondi, Francesca Perondi, Marcelo Perondi e Marco Perondi</FILHOS>
    <LEGISLATURAS>1979-1983 e 1983-1987.</LEGISLATURAS>
    <MANDATOSELETIVOS>Vereador, 1963/1969, Iju&#237;, RS, ; Prefeito, 1973-1976, Iju&#237;, RS, ARENA; Deputado Federal, 1979-1983, RS, PDS. Dt. Posse: 01/02/1979; Deputado Federal, 1983-1987, RS, PDS. Dt. Posse: 01/02/1983.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>ARENA; PDS; PPR, 1993-; PPB, 1995-.</FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES></SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS>Membro, diret&#243;rio naci</ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Um dos fundadores, Jornal da Manh&#227;, Iju&#237;, RS, 1974</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>T&#233;c. em Contabilidade, Escola T&#233;c. de Iju&#237;.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES>C&#194;MARA DOS DEPUTADOS:&#10;COMISS&#213;ES PERMANENTES: Agricultura e Pol&#237;tica Rural: Membro, 1979-1983; Transportes: Suplente, 1979 e 1981.</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS>Membro, Sociedade Ci</ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS>Miss&#227;o Cultural, EUA, 1979; Miss&#227;o Cultural, EUA,  1981; Miss&#227;o Cultural, Jamahiriya &#193;rabe Popular Socialista da L&#237;bi</MISSOESOFICIAS>
    <OUTRASINFORMACOES>Seu irm&#227;o, Darc&#237;sio</OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 27/06/1985 a 16/10/1985, SC, PDS. Dt. Posse: 27/06/1985.</MANDATOSCD>
    <MANDATOSEXTERNOS></MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>123129</CODPESSOA>
    <TXTNOMEPARLAMENTAR>ENIO ANDRADE BRANCO</TXTNOMEPARLAMENTAR>
    <TXTNOME>Enio Andrade Branco</TXTNOME>
    <IDECADASTRO>131903</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR></NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>47</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PFL</SIGPARTIDO>
    <SIGUFREPRESENTACAO>SC</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>09/06/52</DATNASCIMENTO>
    <NUMCPF>17913802987</NUMCPF>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Lages, SC</NATURALIDADE>
    <PROFISSOES>Advogado e Administrador de Empresas</PROFISSOES>
    <FILIACAO>Jo&#227;o Maria Borges Branco e Diva Andrade Branco</FILIACAO>
    <CONJUGE></CONJUGE>
    <FILHOS></FILHOS>
    <LEGISLATURAS>1983-1987</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 27/06/1985 a 16/10/1985, SC, PDS. Dt. Posse: 27/06/1985.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>PDS, -1985; PFL, 1985-.</FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES>Assumiu, como Suplente, o mandato de Deputado Federal, na Legislatura de 1983-1987, de 27 de junho a 16 de outubro de 1985, na vaga do Deputado Evaldo Amaral.</SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS></ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Advogado, Comp. Des. Est. &#40;CODESC&#41;, SC; Sub-Chefe da Casa Civil, Gov. SC, 1979-1982, Superintendente da Funda&#231;&#227;o Catarinense de Desenvolvimento de Comunidade, FUCADESC.</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Direito; P&#243;s-gradua&#231;&#227;o em Direito Internacional P&#250;blico, Universidade de Nice, Fran&#231;a, 1976; Administra&#231;&#227;o de Empresas.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES></ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS>Presidente do DCE, U</ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES></OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1987, SC, PDS.</MANDATOSCD>
    <MANDATOSEXTERNOS>Vereador, Imaru&#237;/SC, Partido: N/D,&#10;Per&#237;odo:  a &#10;Governador, N/D, Partido: N/D,&#10;Per&#237;odo:  a &#10;Deputado Estadual, SC, Partido: N/D,&#10;Per&#237;odo:  a &#10;Prefeito, Imaru&#237;/SC, Partido: N/D,&#10;Per&#237;odo:  a</MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>123130</CODPESSOA>
    <TXTNOMEPARLAMENTAR>EPITACIO BITTENCOURT</TXTNOMEPARLAMENTAR>
    <TXTNOME>Epit&#225;cio Bittencourt</TXTNOME>
    <IDECADASTRO>131904</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR></NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>47</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PDS</SIGPARTIDO>
    <SIGUFREPRESENTACAO>SC</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>30/11/28</DATNASCIMENTO>
    <NUMCPF>00782165915</NUMCPF>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Imaru&#237;, SC</NATURALIDADE>
    <PROFISSOES>Advogado</PROFISSOES>
    <FILIACAO>Pedro Bittencourt e Margarida Mattos</FILIACAO>
    <CONJUGE>Helena Prada Bittencourt</CONJUGE>
    <FILHOS>Albertina Bittencourt, Margaret Bittencourt, Paulo Bittencourt e Pedro Bittencourt Neto</FILHOS>
    <LEGISLATURAS>1983-1987</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Estadual, 1955 1983, SC, ; Governador, 10/01 a 27/01/1982, , ; Prefeito, 1951 1954, Imaru&#237;, , ; Vereador, 1951, Imaru&#237;, , ; Deputado Federal, -1987, SC, PDS.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>ARENA; PSD; PDS</FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES></SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS>Renunciou ao mandat</RENUNCIAS>
    <ATIVIDADESPARTIDARIAS>L&#237;der, ARENA, 1972, 19</ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Professor Prim&#225;rio, Imaru&#237;, SC; Tesoureiro, Correios, Florian&#243;polis, SC; Conselheiro, Tribunal de Contas, SC, 1986; Vice-Presidente, TCE, SC, 1988; Presidente, TCE, SC, janeiro de 1991 a janeiro de 1993.</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>T&#233;cnico em contabilidade, Academia de Com&#233;rcio de Santa Catarina; Bacharel em Ci&#234;ncias Jur&#237;dicas e Sociais, Universidade Federal de Santa Catarina.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES>C&#194;MARAS MUNICIPAIS, ASSEMBL&#201;IAS LEGISLATIVAS E C&#194;MARA LEGISLATIVA&#10;CM-Imaru&#237;,SC: MESA: Presidente, 1951-1954.&#10;&#10;ALSC:MESA: Terceiro Secret&#225;rio, 1975, 1976; Presidente, 1981-1983.</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS>Visita oficial, a convite do governador de Santa Catarina, Amori, Jap&#227;o, 1985.</MISSOESOFICIAS>
    <OUTRASINFORMACOES>No assentamento ibn</OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1963-1965, MA, UDN. Dt. Posse: 03/04/1963; Deputado Federal, 1975-1979, MA, MDB. Dt. Posse: 01/02/1975; Deputado Federal, 1979-1983, MA, MDB. Dt. Posse: 01/02/1979; Deputado Federal, 1983-1987, MA, PMDB. Dt. Posse: 01/02/1983.</MANDATOSCD>
    <MANDATOSEXTERNOS>Prefeito, S&#227;o Lu&#237;s/MA, Partido: UDN,&#10;Per&#237;odo: 1966 a 1969&#10;Governador, MA, Partido: PMDB,&#10;Per&#237;odo: 1987 a 1990&#10;Senador, MA, Partido: PDC,&#10;Per&#237;odo: 1991 a 1999</MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>123131</CODPESSOA>
    <TXTNOMEPARLAMENTAR>EPIT&#193;CIO CAFETEIRA</TXTNOMEPARLAMENTAR>
    <TXTNOME>Epit&#225;cio Cafeteira Afonso Pereira</TXTNOME>
    <IDECADASTRO>131905</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR>81</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>47</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PMDB</SIGPARTIDO>
    <SIGUFREPRESENTACAO>MA</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>27/06/24</DATNASCIMENTO>
    <NUMCPF></NUMCPF>
    <GRAUINSTRUCAO>Superior Incompleto</GRAUINSTRUCAO>
    <NATURALIDADE>Jo&#227;o Pessoa, PB</NATURALIDADE>
    <PROFISSOES>Banc&#225;rio e T&#233;cnico em Contabilidade</PROFISSOES>
    <FILIACAO>Jos&#233; Justino Pereira e Eud&#243;xia Afonso Pereira</FILIACAO>
    <CONJUGE>Maria Isabel Pinheiro Rodrigues Afonso Pereira</CONJUGE>
    <FILHOS>Jana&#237;na Rodrigues Afonso Pereira</FILHOS>
    <LEGISLATURAS>1963-1967, 1975-1979, 1979-1983 e 1983-1987.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1963-1965, MA, UDN. Dt. Posse: 03/04/1963; Prefeito, 1965-1969, S&#227;o Lu&#237;s, MA, UDN; Deputado Federal, 1975-1979, MA, MDB. Dt. Posse: 01/02/1975; Deputado Federal, 1979-1983, MA, MDB. Dt. Posse: 01/02/1979; Deputado Federal, 1983-1987, MA, PMDB. Dt. Posse: 01/02/1983; Governador, 1987-1990, MA, PMDB; Senador, 1991-1999, MA, PDC.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>UDN; MDB; PMDB; PPB; PMDB; PDC; PPR; PDT</FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES>Assumiu, como Suplente, o mandato de Deputado Federal para a Legislatura 1963-1967, de 3 de abril a 1 de maio de 1963; de 24 de junho a 20 de agosto de 1963; de 2 de setembro a 27 de outubro de 1963; de 20 a 31 de mar&#231;o de 1964; de 15 a 17 de fevereiro de 1965 e de 24 a 29 de mar&#231;o de 1965.</SUPLENCIASEFETIVACOES>
    <LICENCAS>Licenciou-se do man</LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS>Vice-L&#237;der, MDB, 1977;</ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Subchefe de Se&#231;&#227;o, de Servi&#231;o, Contador e Inspetor do Banco do Brasil.</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>T&#233;cnico em contabilidade , Escola T&#233;cnica de Com&#233;rcio de Macei&#243;, 1960.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES>SENADO FEDERAL: &#10;Comiss&#227;o de Educa&#231;&#227;o: Membro; Comiss&#227;o de Rela&#231;&#245;es Exteriores e Defesa Nacional: Membro; Comiss&#227;o de Fiscaliza&#231;&#227;o e Controle: Membro.&#10;&#10;C&#194;MARA DOS DEPUTADOS:&#10;MESA DIRETORA: Segundo-Secret&#225;rio, 1979-1980; Terceiro-Secret&#225;rio, 1985-1986.&#10;&#10;COMISS&#213;ES PERMANENTES: Amaz&#244;nia: Membro efetivo, 1975; Finan&#231;as: Membro, 1975; Fiscaliza&#231;&#227;o Financeira e Tomada de Contas: Suplente, 1975 e 1983; Reda&#231;&#227;o: Presidente, 198</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES>Medalha de Grande Oficial da Ordem do Congresso Nacional.</CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS>Membro da Delega&#231;&#227;o Brasileira &#224;s Reuni&#245;esda Uni&#227;o Interparlamentar, Venezuela, 1979 e Rep&#250;blicaDemocr&#225;tica da Aleman</MISSOESOFICIAS>
    <OUTRASINFORMACOES></OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal &#40;Constituinte&#41;, 1946-1951, PB, UDN. Dt. Posse: 05/02/1946; Deputado Federal, 1951-1955, PB, UDN. Dt. Posse: 01/02/1951; Deputado Federal, 1955-1959, PB, UDN. Dt. Posse: 01/02/1955; Deputado Federal, 1959-1963, PB, UDN. Dt. Posse: 01/02/1959; Deputado Federal, 1963-1967, PB, UDN. Dt. Posse: 01/02/1963; Deputado Federal, 1967-1971, PB, ARENA. Dt. Posse: 01/02/1967; Deputado Federal, 1979-1983, PB, PDS. Dt. Posse: 01/02/1979; Deputado Federal, 1983-1986, PB, PDS. Dt. Posse: 01/02/1983.</MANDATOSCD>
    <MANDATOSEXTERNOS>Deputado Estadual, PB, Partido: PRL,&#10;Per&#237;odo: 1935 a 1939, Constituinte&#10;Governador, PB, Partido: N/D,&#10;Per&#237;odo: 1971 a 1975&#10;Prefeito, Jo&#227;o Pessoa/PB, Partido: N/D,&#10;Per&#237;odo:  a &#10;Prefeito, Patos/PB, Partido: N/D,&#10;Per&#237;odo:  a &#10;Deputado Estadual, PB, Partido: N/D,&#10;Per&#237;odo:  a</MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>123132</CODPESSOA>
    <TXTNOMEPARLAMENTAR>ERNANI SATYRO</TXTNOMEPARLAMENTAR>
    <TXTNOME>Ern&#226;ni Ayres Satyro e Sousa</TXTNOME>
    <IDECADASTRO>131906</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR>82</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>47</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PDS</SIGPARTIDO>
    <SIGUFREPRESENTACAO>PB</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>11/09/11</DATNASCIMENTO>
    <NUMCPF>00026263149</NUMCPF>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Patos, PB</NATURALIDADE>
    <PROFISSOES>Agricultor e Advogado</PROFISSOES>
    <FILIACAO>Miguel Satyro e Sousa e Capitulina Ayres Satyro e Sousa</FILIACAO>
    <CONJUGE>Antonieta Sayro</CONJUGE>
    <FILHOS>Bertholdo Satyro e Sousa, Gleide Satyro e Sil&#234;de Satyro S&#225; Leite</FILHOS>
    <LEGISLATURAS>1946-1951, 1951-1955, 1955-1959, 1959-1963, 1963-1967, 1967-1971, 1979-1983 e 1983-1987.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Estadual, , PB, ; Prefeito, , Patos, PB, ; Prefeito, 1940, Jo&#227;o Pessoa, , ; Deputado Estadual &#40;Constituinte&#41;, 1935-1939, PB, PRL; Deputado Federal &#40;Constituinte&#41;, 1946-1951, PB, UDN. Dt. Posse: 05/02/1946; Deputado Federal, 1951-1955, PB, UDN. Dt. Posse: 01/02/1951; Deputado Federal, 1955-1959, PB, UDN. Dt. Posse: 01/02/1955; Deputado Federal, 1959-1963, PB, UDN. Dt. Posse: 01/02/1959; Deputado Federal, 1963-1967, PB, UDN. Dt. Posse: 01/02/1963; Deputado Federal, 1967-1971, PB, ARENA. Dt. Posse: 01/02/1967; Governador, 1971-1975, PB, ; Deputado Federal, 1979-1983, PB, PDS. Dt. Posse: 01/02/1979; Deputado Federal, 1983-1986, PB, PDS. Dt. Posse: 01/02/1983.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>ARENA; UDN</FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES></SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS>Renunciou ao mandat</RENUNCIAS>
    <ATIVIDADESPARTIDARIAS>Vice-Lider, L&#237;der e Se</ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Chefe de Pol&#237;cia, PB, 1939; Ministro, Superior Tribunal Militar.</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Col&#233;gio Pio X; Liceu Paraibano de Jo&#227;o Pessoa, PB; Bacharel em Ci&#234;ncias Jur&#237;dicas e Sociais, Fac. de Direito, Recife, PE, 1933; Especializa&#231;&#227;o em Direito Penal.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES>C&#194;MARA DOS DEPUTADOS - Legislaturas anteriores &#224; 54&#170;:&#10;COMISS&#213;ES PERMANENTES: Constitui&#231;&#227;o e Justi&#231;a: Presidente, 1980, Membro efetivo, 1979 e 1981, e Suplente, 1967-1968; Finan&#231;as e Or&#231;amento: Membro efetivo, 1963; Legisla&#231;&#227;o Social: Membro; Rela&#231;&#245;es Exteriores: Suplente, 1979-1981; Reda&#231;&#227;o: Suplente, 1981.&#10;COMISS&#213;ES ESPECIAIS: Reforma Eleitoral, Presidente, 1951; Reforma do C&#243;digo Civil - Direito das Coisas, Relator, 1</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS>Sousa, Ern&#226;ni Ayres Satyro e. Mariana, 1956.&#10;_____. Quadro Negro,1952; O novo conceito de leg&#237;tima defesa.&#10;_____. Direito penal militar e seguran&#231;a nacional: ac&#243;rd&#227;os, votos e despachos, 19</OBRASPUBLICADAS>
    <MISSOESOFICIAS>Observador da CD na Confer&#234;ncia Internacional do Trabalho, Genebra, 1947.</MISSOESOFICIAS>
    <OUTRASINFORMACOES>Pai, Miguel S&#225;tiro </OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1975-1979, SC, . Dt. Posse: 01/02/1975; Deputado Federal, 1979-1983, SC, PMDB. Dt. Posse: 01/02/1979; Deputado Federal, 1985, SC, . Dt. Posse: 16/05/1985.</MANDATOSCD>
    <MANDATOSEXTERNOS>Vereador, Erechim/RS, Partido: N/D,&#10;Per&#237;odo:  a &#10;Vereador, Erechim/RS, Partido: N/D,&#10;Per&#237;odo:  a</MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>123133</CODPESSOA>
    <TXTNOMEPARLAMENTAR>ERNESTO DE MARCO</TXTNOMEPARLAMENTAR>
    <TXTNOME>Ernesto Jos&#233; de Marco</TXTNOME>
    <IDECADASTRO>131907</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR>83</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>47</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>MDB</SIGPARTIDO>
    <SIGUFREPRESENTACAO>SC</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>25/10/18</DATNASCIMENTO>
    <NUMCPF>00312029934</NUMCPF>
    <GRAUINSTRUCAO></GRAUINSTRUCAO>
    <NATURALIDADE>Bento Gon&#231;alves, RS</NATURALIDADE>
    <PROFISSOES>Comerciante</PROFISSOES>
    <FILIACAO>Ricardo de Marco e Cec&#237;lia de Marco</FILIACAO>
    <CONJUGE>Maria Ana de Marco</CONJUGE>
    <FILHOS>Altair Jos&#233;, Ari Jos&#233;, Diomedes, Geno&#237;no Ant&#244;nio e Sadi Jos&#233;</FILHOS>
    <LEGISLATURAS>1975-1979, 1979-1983 e 1983-1987.</LEGISLATURAS>
    <MANDATOSELETIVOS>Vereador, 1947-1951, Erechim, RS, ; Vereador, 1951-1955, Erechim, RS, ; Deputado Federal, 1975-1979, SC, . Dt. Posse: 01/02/1975; Deputado Federal, 1979-1983, SC, PMDB. Dt. Posse: 01/02/1979; Deputado Federal, 1985, SC, . Dt. Posse: 16/05/1985.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS></FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES></SUPLENCIASEFETIVACOES>
    <LICENCAS></LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS></ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS></ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS></ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES>C&#194;MARA DOS DEPUTADOS:&#10;COMISS&#213;ES PERMANENTES: Agricultura e Pol&#237;tica Rural: Suplente, 1975 e 1979-1981; Fiscaliza&#231;&#227;o Financeira e Tomada de Contas: Membro, 1975 e 1980-1981 e Vice-Presidente, 1979; Transportes: Suplente, 1975 e 1979. &#10;COMISS&#213;ES ESPECIAIS: Desenvolvimento da Regi&#227;o Sul: Vice-Presidente, 1976.</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES></CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>
    <MISSOESOFICIAS></MISSOESOFICIAS>
    <OUTRASINFORMACOES></OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <MANDATOSCD>Deputado Federal, 1987, SP, PDS.</MANDATOSCD>
    <MANDATOSEXTERNOS>Prefeito, Suzano/SP, Partido: N/D,&#10;Per&#237;odo:  a &#10;Vereador, Suzano/SP, Partido: N/D,&#10;Per&#237;odo:  a</MANDATOSEXTERNOS>
    <NUMGABINETE></NUMGABINETE>
    <ANEXO></ANEXO>
    <ANDAR></ANDAR>
    <TELEFONE></TELEFONE>
    <FAX></FAX>
    <CODPESSOA>123134</CODPESSOA>
    <TXTNOMEPARLAMENTAR>ESTEVAM GALVAO</TXTNOMEPARLAMENTAR>
    <TXTNOME>Estevam Galv&#227;o de Oliveira</TXTNOME>
    <IDECADASTRO>131908</IDECADASTRO>
    <NUMCARTEIRAPARLAMENTAR></NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>47</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PDS</SIGPARTIDO>
    <SIGUFREPRESENTACAO>SP</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>15/08/42</DATNASCIMENTO>
    <NUMCPF>05506280882</NUMCPF>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Gar&#231;a, SP</NATURALIDADE>
    <PROFISSOES>Advogado</PROFISSOES>
    <FILIACAO>Jos&#233; Galv&#227;o de Oliveira e &#194;ngela Martins de Oliveira</FILIACAO>
    <CONJUGE>Viviane Domschke Galv&#227;o de Oliveira</CONJUGE>
    <FILHOS>Daniella Galv&#227;o de Oliveira</FILHOS>
    <LEGISLATURAS>1983-1987</LEGISLATURAS>
    <MANDATOSELETIVOS>Prefeito, 1977 1982, Suzano, SP, ; Vereador, 1972 1976, Suzano, SP, ; Deputado Federal, -1987, SP, PDS.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS></FILIACOESPARTIDARIAS>
    <AFASTAMENTOS></AFASTAMENTOS>
    <SUPLENCIASEFETIVACOES></SUPLENCIASEFETIVACOES>
    <LICENCAS>Licenciou-se do man</LICENCAS>
    <PERDASMANDATO></PERDASMANDATO>
    <RENUNCIAS></RENUNCIAS>
    <ATIVIDADESPARTIDARIAS></ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Escritur&#225;rio, Prefeitura de Suzano, SP, 1961; Fiscal Lan&#231;ador, 1968; Chefe da Se&#231;&#227;o do  Expediente, 1969; Diretor da Receita - Prefeitura Municipal de Suzano, SP; Presidente, do Conselho do Instituto de Previd&#234;ncia do Estado de S&#227;o Paulo &#40;IPESP&#41;.</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Bacharel em Ci&#234;ncias Jur&#237;dicas e Sociais, Fac. de Direito Braz Cubas de Mogi das Cruzes, SP; Curso de Aperfei&#231;oamento em Tributos Municipais; Curso intensivo de Administra&#231;&#227;o Municipal, Serra Negra, Guaruj&#225; e Itanha&#233;m; Curso de Legisla&#231;&#227;o Tribut&#225;ria - IBAM; Curso Problemas  Brasileiros; Curso de Aspectos M&#233;dico-Legais da Criminologia.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS></SEMINARIOS>
    <ATIVIDADESPARLAMENTARES>C.D.:&#10;COMISS&#213;ES: Economia Ind&#250;stria e Com&#233;rcio, Membro, 1983; Agricultura e Pol&#237;tica Rural, Suplente, 1983.&#10;CM-Suzano-SP: Presidente da Comiss&#227;o de Finan&#231;as e Or&#231;amento e de V&#225;rias Comiss&#245;es Especiais.&#10;MESA: Secret&#225;rio</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS></ATIVIDADESSINDICAIS>
    <CONSELHOS></CONSELHOS>
    <CONDECORACOES>T&#237;tulo de Cidad&#227;o Poaense, Po&#225;, SP.</CONDECORACOES>
    <OBRASPUBLICADAS></OBRASPUBLICADAS>